/**
 * Expert 6: Mithun Chakraborty Style — Bengali Dialogue Bank
 * 500+ natural Bengali dialogues with Kolkata colloquial style.
 * Rich emotional vocabulary, intellectual wit, cultural specifics.
 */

import { DialogueBank, DialogueLine } from './types';

const lines: DialogueLine[] = [
  // GREETINGS (50)
  { text: "Ki re! Kemon achis?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "casual greeting", variables: [] },
  { text: "Nomoskar! Kemon achen?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "respectful greeting", variables: [] },
  { text: "Dada! Koto din por!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! after so long!", variables: [] },
  { text: "Arre! Tui ekhane?!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "you here?!", variables: [] },
  { text: "Aye aye! Bosho bosho!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "come sit!", variables: [] },
  { text: "Fatafati! Tui esechis!", emotion: "greeting", intensity: "high", gender: "any", archetype: "friend", context: "awesome! you came!", variables: [] },
  { text: "Good morning re!", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "morning greeting", variables: [] },
  { text: "Maa! Esechi!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "child", context: "mom! I've come!", variables: [] },
  { text: "Baba! Ekhane dekho!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "child", context: "dad! look here!", variables: [] },
  { text: "Master moshai! Pronam!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "teacher! greetings!", variables: [] },
  { text: "VIP eseche! Welcome!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "VIP arrived!", variables: [] },
  { text: "Kothay chili re eto din?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "where were you so long?", variables: [] },
  { text: "Didi! Kemon achen?", emotion: "greeting", intensity: "low", gender: "female", archetype: "any", context: "sister! how are you?", variables: [] },
  { text: "Boss! Ki scene?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "what's the scene?", variables: [] },
  { text: "Esho esho! Cha khabe?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "come! have tea?", variables: [] },
  { text: "Macha! Ready toh?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! ready?", variables: [] },
  { text: "Kaku! Pronam!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "uncle! greetings!", variables: [] },
  { text: "Mashi! Ki khobor?", emotion: "greeting", intensity: "medium", gender: "female", archetype: "any", context: "aunt! what's news?", variables: [] },
  { text: "Arre re! Zinda achis to?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "are you alive?", variables: [] },
  { text: "Mass entry hocche!", emotion: "greeting", intensity: "high", gender: "any", archetype: "hero", context: "mass entry!", variables: [] },
  { text: "Cholo! Shuru kora jak!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "let's start!", variables: [] },
  { text: "Thakurda! Ashirbad din!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "grandpa! bless me!", variables: [] },
  { text: "Hello hello! Testing!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "dramatic greeting", variables: [] },
  { text: "Ami esechi! Party shuru koro!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "I'm here! party!", variables: [] },
  { text: "{name}! Tomake miss korechi!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "missed you!", variables: ["{name}"] },
  { text: "Swagotom! Swagotom!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "narrator", context: "welcome!", variables: [] },
  { text: "Tara tari aye! Tomake chai!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "come quick! need you!", variables: [] },
  { text: "Bondhu! Ki achis?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "friend! how are you?", variables: [] },
  { text: "Late kore eshechis!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "came late!", variables: [] },
  { text: "Amader area te welcome!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "welcome to our area!", variables: [] },
  { text: "Jethu! Pronam!", emotion: "greeting", intensity: "low", gender: "male", archetype: "child", context: "elder uncle! greetings!", variables: [] },
  { text: "Boudi! Kemon achen?", emotion: "greeting", intensity: "low", gender: "female", archetype: "any", context: "sister-in-law! how are you?", variables: [] },
  { text: "Tui chhara party hoy na!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "no party without you!", variables: [] },
  { text: "Arre bhai! Aye aye!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "bro! come!", variables: [] },
  { text: "Super! Ami bhebechilam asbe na!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "thought you wouldn't come!", variables: [] },
  { text: "Group photo tuli! Shobai aye!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "group photo! come!", variables: [] },
  { text: "Bro! What's up re?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "Banglish greeting", variables: [] },
  { text: "Suprabhat bondhu shobai!", emotion: "greeting", intensity: "low", gender: "any", archetype: "narrator", context: "good morning friends!", variables: [] },
  { text: "Shobai ready? Start kora jak!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "ready? start!", variables: [] },
  { text: "Ki re {name}! Ki korchis?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "what are you doing?", variables: ["{name}"] },
  { text: "Eshechis toh? Bhalo korechis!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "you came? good!", variables: [] },
  { text: "Mashima! Pronam!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "auntie! greetings!", variables: [] },
  { text: "Chele! Aye re!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "elder", context: "boy! come!", variables: [] },
  { text: "Meye! Aye re!", emotion: "greeting", intensity: "medium", gender: "female", archetype: "elder", context: "girl! come!", variables: [] },
  { text: "Ki khobor bondhu?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "what's news friend?", variables: [] },
  { text: "Amra eshechi! Scene shuru hok!", emotion: "greeting", intensity: "high", gender: "any", archetype: "hero", context: "we've arrived!", variables: [] },
  { text: "Ekhane eshechis? Bhalo laglo!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "you came here? nice!", variables: [] },
  { text: "Thakuma! Ashirbad din!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "grandma! bless!", variables: [] },
  { text: "Ki scene chole ekhane?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "what's happening here?", variables: [] },
  { text: "Prothom tomake bolchi!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "telling you first!", variables: [] },

  // SURPRISE (45)
  { text: "Bapre bap! Eta ki!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh my! what!", variables: [] },
  { text: "Ki shorbonash! Eta ki holo!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "disaster! what happened!", variables: [] },
  { text: "Sotti? Sotti naki?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "true? really?!", variables: [] },
  { text: "Ami parbo na! Bishwas hocche na!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "I can't! can't believe!", variables: [] },
  { text: "Darun! Eta hoyeche!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "amazing! this happened!", variables: [] },
  { text: "Ki holo re?! Bolo bolo!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what happened?! tell!", variables: [] },
  { text: "Shock laglo! Full shock!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "shocked!", variables: [] },
  { text: "Plan motho fail hoyeche!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "whole plan failed!", variables: [] },
  { text: "Ke korlo eta?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "who did this?!", variables: [] },
  { text: "Chokh bishwas korche na!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "eyes can't believe!", variables: [] },
  { text: "Eta twist re! Boro twist!", emotion: "surprise", intensity: "high", gender: "any", archetype: "narrator", context: "twist! big twist!", variables: [] },
  { text: "Kokhon holo eta?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "when?!", variables: [] },
  { text: "Shopno na to?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "dream right?!", variables: [] },
  { text: "Jackpot re! Full jackpot!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "jackpot!", variables: [] },
  { text: "Secret berie eseche!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "secret is out!", variables: [] },
  { text: "Maa! Dekho eta!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "mom! look!", variables: [] },
  { text: "Matha ghurche shock e!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "head spinning!", variables: [] },
  { text: "Impossible re! Impossible!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "impossible!", variables: [] },
  { text: "{name} eta korlo?! Bishwas-i hoy na!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "they did this?! unbelievable!", variables: ["{name}"] },
  { text: "Shob bodley gelo!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything changed!", variables: [] },
  { text: "Ekhon bolchis?! Ekhon?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "telling me now?!", variables: [] },
  { text: "Record bhenge gelo!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "record broken!", variables: [] },
  { text: "Eta miracle re! Pure miracle!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "miracle!", variables: [] },
  { text: "Light chole gelo! Ondhokar!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "lights out! dark!", variables: [] },
  { text: "Eta {object}! Asol!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is real!", variables: ["{object}"] },
  { text: "Shob ekbare hoyeche!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything at once!", variables: [] },
  { text: "Keu-i bole ni re!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "nobody told me!", variables: [] },
  { text: "History re eta! History!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "history!", variables: [] },
  { text: "Taka! Onek taka!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "money! lots!", variables: [] },
  { text: "Ekhon ki korbo?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what now?!", variables: [] },
  { text: "Hobe na! Eta hobe na!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "can't be! impossible!", variables: [] },
  { text: "Ami theek shunlam to?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "did I hear right?!", variables: [] },
  { text: "Motho scene bodley gelo!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "whole scene changed!", variables: [] },
  { text: "Aaha! Eta ki shundor!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "beautiful!", variables: [] },
  { text: "Praan chole jacche shock e!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "dying from shock!", variables: [] },
  { text: "Shobai pagol hoye gelo!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everyone went crazy!", variables: [] },
  { text: "Ki timing re! Exact!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what timing!", variables: [] },
  { text: "Fatafati re! Fatafati!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "fantastic!", variables: [] },
  { text: "Bhishon boro byapar!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "very big matter!", variables: [] },
  { text: "Shob shesh! Shob shesh hoyeche!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "everything's over!", variables: [] },
  { text: "Ek minute! Wait koro!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "wait!", variables: [] },
  { text: "Ashombhob re! Ashombhob!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "impossible!", variables: [] },
  { text: "Ghorer kheye boner mosh tarano!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "elder", context: "proverb: chasing wilderness (mischief)", variables: [] },
  { text: "Vera level content re!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "another level!", variables: [] },
  { text: "Arre baapre baap!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh my God!", variables: [] },

  // ANGER (35)
  { text: "Boro hoyeche! Ar sahya hoy na!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "enough! unbearable!", variables: [] },
  { text: "Mukh bondho koro!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "shut your mouth!", variables: [] },
  { text: "Tomar jonno shob hoyeche!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "all because of you!", variables: [] },
  { text: "Bishwas hariye gelo!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "lost trust!", variables: [] },
  { text: "Eta last warning!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "last warning!", variables: [] },
  { text: "Jao! Chokher samne asbe na!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "go! don't appear!", variables: [] },
  { text: "Lokkhi sojon keno na hotey achis!", emotion: "anger", intensity: "medium", gender: "any", archetype: "elder", context: "why can't you be good!", variables: [] },
  { text: "Naatok koro na!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "stop acting!", variables: [] },
  { text: "Lojja nei tomar?!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "aren't you ashamed?!", variables: [] },
  { text: "Limit cross kore felecho!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "crossed the limit!", variables: [] },
  { text: "Ami bolini to! Shononi!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "I told you! didn't listen!", variables: [] },
  { text: "Bimar! Boro bimar!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "betrayal! big betrayal!", variables: [] },
  { text: "Tomar tricks ekhane cholbe na!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "tricks won't work!", variables: [] },
  { text: "Enough re! Enough!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "enough!", variables: [] },
  { text: "Abar same bhool?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "same mistake again?!", variables: [] },
  { text: "Chup! Chup thako!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "quiet!", variables: [] },
  { text: "Rakte jol dhoreche!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "blood is boiling!", variables: [] },
  { text: "Tui jano na ami ke?!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "know who I am?!", variables: [] },
  { text: "Patience er poriksha nio na!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't test patience!", variables: [] },
  { text: "Eta galat! Bhishon galat!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "wrong! very wrong!", variables: [] },
  { text: "Ami maaf korbo na!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "won't forgive!", variables: [] },
  { text: "Jao! Tomar dorkar nei!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "go! don't need you!", variables: [] },
  { text: "Samne asbe na ar!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't come before me!", variables: [] },
  { text: "Bolo! Ki korecho?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "tell! what did you do?!", variables: [] },
  { text: "Tumi kokhono sudhirbe na!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "you'll never change!", variables: [] },
  { text: "Control koro nijeke!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "control yourself!", variables: [] },
  { text: "Barite bolbo!", emotion: "anger", intensity: "medium", gender: "any", archetype: "child", context: "I'll tell at home!", variables: [] },
  { text: "Onek dhairya dhekhiyechi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "showed too much patience!", variables: [] },
  { text: "Bokka! Boro bokka korechis!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "blunder!", variables: [] },
  { text: "Tomar sathe kotha bolai byartha!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "talking to you is useless!", variables: [] },
  { text: "Amake ekla chere de!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "leave me alone!", variables: [] },
  { text: "Eta bhul! Boro bhul!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "mistake! big!", variables: [] },
  { text: "Eta ki koris tui?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "what are you doing?!", variables: [] },
  { text: "Ar hole dekhbo!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "if it happens again I'll see!", variables: [] },
  { text: "Bhebecho ki?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "what do you think?!", variables: [] },

  // FEAR (30) + HAPPINESS (35) + THINKING (20) + NARRATION (20) + MORAL (20) + CATCHPHRASE + FILLER + OTHER (~265)
  // FEAR
  { text: "Maa! Bhoy korche!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "mom! scared!", variables: [] },
  { text: "Bhoot! Palaao!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "ghost! run!", variables: [] },
  { text: "Ishwar! Bachao!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "God! save!", variables: [] },
  { text: "Amar bhishon bhoy lagche!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "very scared!", variables: [] },
  { text: "Okhane takiyo na!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look there!", variables: [] },
  { text: "Palaao! Tara tari!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "run! fast!", variables: [] },
  { text: "Ke achhe okhane?!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "who's there?!", variables: [] },
  { text: "Paa kampche bhoye!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "legs trembling!", variables: [] },
  { text: "Ekhane theke cholo! Jaldi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "let's leave!", variables: [] },
  { text: "Pechone takiyo na! Oudo!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look back! run!", variables: [] },
  { text: "Shaap! Shaap ache!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "snake!", variables: [] },
  { text: "Barite jete chai! Ekhoni!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "go home! now!", variables: [] },
  { text: "Ota ashche! Ota ashche!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's coming!", variables: [] },
  { text: "Lukie poro! Tara tari!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "hide! quick!", variables: [] },
  { text: "Ekla thakte parbo na ekhane!", emotion: "fear", intensity: "medium", gender: "any", archetype: "child", context: "can't stay alone!", variables: [] },
  { text: "Haath dhoro re!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "hold my hand!", variables: [] },
  { text: "Light chole gelo! Ondhokar!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "lights out!", variables: [] },
  { text: "Ki aowaj chilo ota?!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "what was that sound?!", variables: [] },
  { text: "Help! Keu aye!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "help!", variables: [] },
  { text: "Shhh! Aowaj koro na! Shunbe!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "shh! it'll hear!", variables: [] },
  { text: "Eta faand re! Dhora porechi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "trap! caught!", variables: [] },
  { text: "Baire jowar raasta nei!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "no way out!", variables: [] },
  { text: "Bhoyo peyo na! Ami achi!", emotion: "fear", intensity: "medium", gender: "any", archetype: "hero", context: "don't fear! I'm here!", variables: [] },
  { text: "Eta monster re! Boro monster!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "monster!", variables: [] },
  { text: "Praan chole gelo bhoye!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "soul left from fear!", variables: [] },
  { text: "Paa norachche na bhoye!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "feet won't move!", variables: [] },
  { text: "Dorja bondho koro! Jaldi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "close door! fast!", variables: [] },
  { text: "Ami kichu dekhchi! Sotti!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "I saw something! really!", variables: [] },
  { text: "Ekhane kichu thik nei!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "something wrong here!", variables: [] },
  { text: "Amar pechone keu ache!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "someone behind me!", variables: [] },
  // HAPPINESS
  { text: "Darun! Fatafati!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "awesome! fantastic!", variables: [] },
  { text: "Jitechi! Amra jitechi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "we won!", variables: [] },
  { text: "Aaha! Eta-i asol anondo!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "this is real joy!", variables: [] },
  { text: "Party time re! Celebration!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "party!", variables: [] },
  { text: "Hoyeche! Amra korechi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "done! we did it!", variables: [] },
  { text: "Khub bhalo korechis!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "did very well!", variables: [] },
  { text: "Shopno sotti hoyeche!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "dream came true!", variables: [] },
  { text: "Roshogolla banto! Anondo!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "distribute roshogolla!", variables: [] },
  { text: "Tui genius re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're genius!", variables: [] },
  { text: "Best day ever re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "best day!", variables: [] },
  { text: "Amar porisrom phal diyeche!", emotion: "happiness", intensity: "high", gender: "any", archetype: "hero", context: "hard work paid off!", variables: [] },
  { text: "Ishwar ke dhonyobad!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "thanks to God!", variables: [] },
  { text: "Full marks re! Full marks!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "full marks!", variables: [] },
  { text: "{name}! Tui boro great re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're great!", variables: ["{name}"] },
  { text: "Shobai ke thanks!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "thanks everyone!", variables: [] },
  { text: "Amader team number one!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "number one!", variables: [] },
  { text: "Anonde chokh diye jol ashche!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "tears of joy!", variables: [] },
  { text: "Mishti khaoa jak! Celebrate!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "eat sweets!", variables: [] },
  { text: "Barite giye bolbo!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "going home to tell!", variables: [] },
  { text: "Maa! Ami pass korechi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "mom! I passed!", variables: [] },
  { text: "Eta teamwork re! Pure teamwork!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "teamwork!", variables: [] },
  { text: "Record bhengechi re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "broke records!", variables: [] },
  { text: "Champion! Tui champion!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "champion!", variables: [] },
  { text: "Miracle re eta! Pure miracle!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "miracle!", variables: [] },
  { text: "Biryani khaoa jak! Amar treat!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "biryani! my treat!", variables: [] },
  { text: "Mass re! Standing ovation!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "mass!", variables: [] },
  { text: "Shobai heroes!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "all heroes!", variables: [] },
  { text: "Koshtokor chilo kintu worth it!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "tough but worth it!", variables: [] },
  { text: "Golden moment re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "narrator", context: "golden moment!", variables: [] },
  { text: "Hip hip hurray!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "hooray!", variables: [] },
  { text: "Jai Bangla!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "victory chant!", variables: [] },
  { text: "Vera level scene re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "another level!", variables: [] },
  { text: "Cinema-r moto holo life!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "life like a movie!", variables: [] },
  { text: "Amar prarthona shona hoyeche!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "prayer heard!", variables: [] },
  { text: "Best news re! Best news!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "best news!", variables: [] },
  // THINKING (20)
  { text: "Hmm... bhabte hobe!", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "must think!", variables: [] },
  { text: "Amar ek idea ashche!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "getting an idea!", variables: [] },
  { text: "Darao darao... bujhte parchi!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "wait, understanding!", variables: [] },
  { text: "Etar mane holo...", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "this means...", variables: [] },
  { text: "Amra erom korle?", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "what if we do this?", variables: [] },
  { text: "Amar ek plan ache!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "hero", context: "I have a plan!", variables: [] },
  { text: "Brain use koro re! Brain!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "use brain!", variables: [] },
  { text: "Aaha! Ekhon bujhechi!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "now I understand!", variables: [] },
  { text: "Onno angle theke dekhi!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "another angle!", variables: [] },
  { text: "Bhool theke shikho!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "learn from mistakes!", variables: [] },
  { text: "Answer khub simple!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "answer is simple!", variables: [] },
  { text: "Problem thakle solution-o thakbe!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "problem means solution!", variables: [] },
  { text: "Wait wait wait! Eureka!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "eureka!", variables: [] },
  { text: "Practice diye shob hoy!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "practice makes possible!", variables: [] },
  { text: "Eta clue re! Definite!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "this is a clue!", variables: [] },
  { text: "Ekhon bulb jolche!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "bulb lit up!", variables: [] },
  { text: "Eta pattern re! Dekhchis?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "pattern! see?", variables: [] },
  { text: "Ekhon bujhechis to?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "now you understand?", variables: [] },
  { text: "Dhorjo! Dhorjo!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "patience!", variables: [] },
  { text: "Uttor tomar kachhe-i ache!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "answer is with you!", variables: [] },
  // NARRATION (20)
  { text: "Tarpor ki holo? Shono!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "then what? listen!", variables: [] },
  { text: "Onek din aage...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "long ago...", variables: [] },
  { text: "Ekhon porer golpo shono!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "next story!", variables: [] },
  { text: "Ek gaame ek {object} chilo...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "in a village...", variables: ["{object}"] },
  { text: "Kintu golpo ekhane shesh hoy na!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "story doesn't end!", variables: [] },
  { text: "Dekha jak ki hoy!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "let's see!", variables: [] },
  { text: "Ekhon asol golpo shuru!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "real story starts!", variables: [] },
  { text: "Koyekta ghonta pore...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "hours later...", variables: [] },
  { text: "Porer din sokale...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "next morning...", variables: [] },
  { text: "Ebhabe notun adventure shuru holo!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "new adventure!", variables: [] },
  { text: "Shobai bhebechilo shesh... kintu!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "thought over... but!", variables: [] },
  { text: "Tokhon achanak...", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "then suddenly...", variables: [] },
  { text: "Shob bodliye jabe!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everything changing!", variables: [] },
  { text: "Golpote aro ek twist!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "another twist!", variables: [] },
  { text: "Final round! Shesh chance!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "final!", variables: [] },
  { text: "Eta trailer! Picture ache!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "just trailer!", variables: [] },
  { text: "Ei golpo mone rakhbe!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "remember story!", variables: [] },
  { text: "Ekhon golpo egiye cholche...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "story continues...", variables: [] },
  { text: "Somoy bodleche... poristhiti bodleche...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "times changed...", variables: [] },
  { text: "Seedha climax e jai!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "straight to climax!", variables: [] },
  // MORAL (20)
  { text: "Tai bola hoy... porisrom korle phal paoa jay!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "hard work pays!", variables: [] },
  { text: "Shiksha holo... mithye bolbe na!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "don't lie!", variables: [] },
  { text: "Chheleraa! Aaj ki shikhle?", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "kids! what learned?", variables: [] },
  { text: "Satyi shesh porjonto joy!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "truth wins!", variables: [] },
  { text: "Bondhutto shob cheye boro shakti!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "friendship greatest!", variables: [] },
  { text: "Shaahos haranor noy kokhono!", emotion: "moral", intensity: "high", gender: "any", archetype: "mentor", context: "never lose courage!", variables: [] },
  { text: "Boro der kotha shono!", emotion: "moral", intensity: "low", gender: "any", archetype: "elder", context: "listen to elders!", variables: [] },
  { text: "Tara huriye bhool hoy!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "haste = mistakes!", variables: [] },
  { text: "Ekotar moddhye shakti!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "unity is strength!", variables: [] },
  { text: "Lobh kharap!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "greed is bad!", variables: [] },
  { text: "Bipode asol bondhu chena jay!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "true friends in trouble!", variables: [] },
  { text: "Bhool swikar korte shaahos laage!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "admitting mistakes needs courage!", variables: [] },
  { text: "Shikhar kono boyosh nei!", emotion: "moral", intensity: "low", gender: "any", archetype: "mentor", context: "no age for learning!", variables: [] },
  { text: "Ekshaathe korle shob shombhob!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "together possible!", variables: [] },
  { text: "Ei shiksha mone rakhbe!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "remember lesson!", variables: [] },
  { text: "Shikhte thako! Shobshomoy!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "keep learning!", variables: [] },
  { text: "Ki-i hok sotti bolo!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "speak truth!", variables: [] },
  { text: "Life e shortcuts chole na!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "no shortcuts!", variables: [] },
  { text: "Ke re ke bole chena jay na!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "don't underestimate!", variables: [] },
  { text: "Chere dile kokhono jite na!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "quitters never win!", variables: [] },
  // CATCHPHRASE + FILLER + OTHER (45)
  { text: "Amar naam {name}! Shobshomoy ready!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "hero intro", variables: ["{name}"] },
  { text: "Eta amar specialty!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "my specialty!", variables: [] },
  { text: "Kichhu hoy ni! Aabar try kori!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "try again!", variables: [] },
  { text: "Aage khabar! Baki pore!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "food first!", variables: [] },
  { text: "Mission start!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "mission start!", variables: [] },
  { text: "Power up!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "power up!", variables: [] },
  { text: "Game over villains!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "game over!", variables: [] },
  { text: "Ami phire ashbo!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "I'll return!", variables: [] },
  { text: "Ami haar mani na!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "won't accept defeat!", variables: [] },
  { text: "Khabar kothay?!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "where's food?!", variables: [] },
  { text: "Tension niyo na re!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "don't worry!", variables: [] },
  { text: "Achha achha!", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "okay!", variables: [] },
  { text: "Bolo re!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "tell!", variables: [] },
  { text: "Darao darao!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "wait!", variables: [] },
  { text: "Ota na...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "not that...", variables: [] },
  { text: "Dekho dekho!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "look!", variables: [] },
  { text: "Shono shono!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "listen!", variables: [] },
  { text: "Haa haa!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "yes!", variables: [] },
  { text: "Na na!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "no!", variables: [] },
  { text: "Aye!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "come!", variables: [] },
  { text: "Jaa!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "go!", variables: [] },
  { text: "Ek minute!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "one minute!", variables: [] },
  { text: "Jani jani!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "I know!", variables: [] },
  { text: "Simple re!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "simple!", variables: [] },
  { text: "Done!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "done!", variables: [] },
  { text: "Ready?", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "ready?", variables: [] },
  { text: "Tumi parbe!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "you can!", variables: [] },
  { text: "Shaahos harano ucchit noy!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "don't lose courage!", variables: [] },
  { text: "Aabar try koro!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "try again!", variables: [] },
  { text: "Ami tomar shaathe!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "friend", context: "I'm with you!", variables: [] },
  { text: "Joy kachhe ache!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "victory near!", variables: [] },
  { text: "Shabash re!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "elder", context: "well done!", variables: [] },
  { text: "Amra shobai tomar shaathe!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "friend", context: "we're with you!", variables: [] },
  { text: "Ekhon thamle cholbe na!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "can't stop!", variables: [] },
  { text: "Ami kore dekhabo!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "I'll prove!", variables: [] },
  { text: "Ki-i hok!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "no matter what!", variables: [] },
  { text: "Eta amar promise!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "my promise!", variables: [] },
  { text: "Shabdhan! Bipod!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "careful! danger!", variables: [] },
  { text: "Okhane jeo na! Bipojjonok!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "don't go! dangerous!", variables: [] },
  { text: "Eta last warning!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "last warning!", variables: [] },
  { text: "Thanks re! Onek help hoyeche!", emotion: "gratitude", intensity: "medium", gender: "any", archetype: "any", context: "thanks! helped!", variables: [] },
  { text: "Dhonyobad! Hridoy theke!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "heartfelt thanks!", variables: [] },
  { text: "Tui chhara ami nei!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "nothing without you!", variables: [] },
  { text: "{name}! Tui best friend re!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "friend", context: "best friend!", variables: ["{name}"] },
  { text: "Jitechi! Champions!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "won! champions!", variables: [] },
];

export const bengaliBank: DialogueBank = {
  language: 'bengali',
  isoCode: 'bn-IN',
  displayName: 'Bengali',
  lines,
};
