/**
 * Expert 4: Jaggesh Style — Kannada Comedy Dialogue Bank
 * 500+ natural Kannada dialogues with Bangalore/North Karnataka slang.
 */

import { DialogueBank, DialogueLine } from './types';

const lines: DialogueLine[] = [
  // GREETINGS (55)
  { text: "Guru! Heg idiya?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "casual Bangalore greeting", variables: [] },
  { text: "Namaskara! Heg iddira?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "respectful greeting", variables: [] },
  { text: "Yenappa! Yelli idde?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "where were you?", variables: [] },
  { text: "Saku maga! Barthiya alla!", emotion: "greeting", intensity: "high", gender: "male", archetype: "friend", context: "enough! you finally came!", variables: [] },
  { text: "Baa baa! Kootko!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "come sit!", variables: [] },
  { text: "Enna ri! Heg iddira?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "North Karnataka greeting", variables: [] },
  { text: "Hogi baa! Ella ready ah?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "come come! everything ready?", variables: [] },
  { text: "Yak ri! Eshtu dina aytu!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "North KA: how many days!", variables: [] },
  { text: "Boss! Scene enu?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "what's the scene?", variables: [] },
  { text: "Aiyyo! Neenu illi?!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "you're here?!", variables: [] },
  { text: "Macha! Long time no see!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! long time!", variables: [] },
  { text: "Good morning guru!", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "morning greeting", variables: [] },
  { text: "Master! Vandane!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "greeting teacher", variables: [] },
  { text: "Amma! Bande!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "child", context: "mom! came!", variables: [] },
  { text: "Appa! Illi nodi!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "child", context: "dad! look here!", variables: [] },
  { text: "Banni banni! Chai kudiyona?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "come! shall we have tea?", variables: [] },
  { text: "Anna! Namaskara!", emotion: "greeting", intensity: "low", gender: "male", archetype: "child", context: "brother! greetings!", variables: [] },
  { text: "Akka! Heg iddira?", emotion: "greeting", intensity: "low", gender: "female", archetype: "any", context: "sister! how are you?", variables: [] },
  { text: "VIP bandidale! Welcome!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "VIP has arrived!", variables: [] },
  { text: "Ready ah guru? Start madona?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "ready? shall we start?", variables: [] },
  { text: "Macha! Supera iddiya?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! doing super?", variables: [] },
  { text: "Yenappa! Enu vishaya?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "what's the matter?", variables: [] },
  { text: "Nann bande! Party shuru madi!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "I'm here! start the party!", variables: [] },
  { text: "Hegidya {name}? Miss madthidde!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "how are you? was missing you!", variables: ["{name}"] },
  { text: "Swagatha! Swagatha!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "narrator", context: "welcome! welcome!", variables: [] },
  { text: "Bega baa! Ninna kaythidivi!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "come quick! waiting for you!", variables: [] },
  { text: "Oho! Meeru kooda bandira?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "oh you came too?", variables: [] },
  { text: "Yenri! Zinda iddira?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "are you alive?", variables: [] },
  { text: "Mass entry guru!", emotion: "greeting", intensity: "high", gender: "male", archetype: "hero", context: "mass entry!", variables: [] },
  { text: "Chikkappa! Heg iddira?", emotion: "greeting", intensity: "low", gender: "male", archetype: "child", context: "uncle! how are you?", variables: [] },
  { text: "Dodappa! Ashirvada kodi!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "elder! give blessings!", variables: [] },
  { text: "Banni banni! Mane olage banni!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "come inside the house!", variables: [] },
  { text: "Maga! Enu madthidya?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "what are you doing?", variables: [] },
  { text: "Hello hello! Testing!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "dramatic greeting", variables: [] },
  { text: "Yella ready ah? Start madona!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "all ready? let's start!", variables: [] },
  { text: "Namma area ge welcome!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "welcome to our area!", variables: [] },
  { text: "Baa guru! Helu helu!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "come! tell tell!", variables: [] },
  { text: "Thamma! Baa illi!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "elder", context: "younger brother! come here!", variables: [] },
  { text: "Yelli hog idde? Phone ettko maaraya!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "where'd you go? pick up the phone!", variables: [] },
  { text: "Chal! Hogoraa!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "let's go!", variables: [] },
  { text: "Super! Bandbitta andkondidde!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "thought you wouldn't come!", variables: [] },
  { text: "Thammi! Banni!", emotion: "greeting", intensity: "medium", gender: "female", archetype: "elder", context: "little sister! come!", variables: [] },
  { text: "Oho! Late ah bandidya!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "came late!", variables: [] },
  { text: "Neen illde party illa!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "no party without you!", variables: [] },
  { text: "Maama! Namaskara!", emotion: "greeting", intensity: "low", gender: "male", archetype: "child", context: "uncle! greetings!", variables: [] },
  { text: "Yappaa! Finally bande!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "finally came!", variables: [] },
  { text: "Group photo togona! Yella banni!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "let's take group photo!", variables: [] },
  { text: "Maga! Ninna miss madidde!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "missed you!", variables: [] },
  { text: "Namasthe ji!", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "polite namaste", variables: [] },
  { text: "Kaalalli super news helthini!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "telling you super news!", variables: [] },
  { text: "Baa baa! Yenu bittu hogbeda!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "come! don't leave anything!", variables: [] },
  { text: "Yen heg iddare andkondidde!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "was wondering how you're doing!", variables: [] },
  { text: "Sigala! Meeting start agatte!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "soon! meeting is starting!", variables: [] },
  { text: "Bro! What's up guru?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "Kanglish greeting", variables: [] },
  { text: "Enna saar! Yella okay ah?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "everything okay sir?", variables: [] },

  // SURPRISE (50)
  { text: "Aiyyo devare!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh God!", variables: [] },
  { text: "Idu enu aytu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what happened?!", variables: [] },
  { text: "Huchchu biddyappa!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "crazy fellow!", variables: [] },
  { text: "Enu?! Nijva?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what?! really?!", variables: [] },
  { text: "Namboke agalla!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "can't believe!", variables: [] },
  { text: "Yenu maadidya?! Heg agoytu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what did you do?! how?!", variables: [] },
  { text: "Shock ayitu! Full shock!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "got shocked!", variables: [] },
  { text: "Appa! Idu nodbeku!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "dad! look at this!", variables: [] },
  { text: "Plan mottha fail agoytu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "entire plan failed!", variables: [] },
  { text: "Yaaru maadiddu idu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "who did this?!", variables: [] },
  { text: "Nanna kannu namble agthilla!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "can't believe my eyes!", variables: [] },
  { text: "Idu twist guru! Dodda twist!", emotion: "surprise", intensity: "high", gender: "any", archetype: "narrator", context: "this is a twist! big twist!", variables: [] },
  { text: "Yavaga aytu idu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "when did this happen?!", variables: [] },
  { text: "Arey! Idu expect madilla!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "didn't expect this!", variables: [] },
  { text: "Jackpot guru! Full jackpot!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "jackpot!", variables: [] },
  { text: "Secret bayata bandiddu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "secret is out!", variables: [] },
  { text: "Kanasu alla tane?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "this isn't a dream right?!", variables: [] },
  { text: "Ella badlaytu?! Yavaga?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything changed?! when?!", variables: [] },
  { text: "Idu {name} maadida?! Namboke agalla!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "{name} did this?! unbelievable!", variables: ["{name}"] },
  { text: "Impossible guru! Im-pos-si-ble!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "impossible!", variables: [] },
  { text: "Talege suttiddu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "head is spinning!", variables: [] },
  { text: "Idu history guru!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is history!", variables: [] },
  { text: "Light hogoytu! Kadalu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "power cut! darkness!", variables: [] },
  { text: "Amma! Nodi idu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "mom! look at this!", variables: [] },
  { text: "Ippa helbthira?! Ippa?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "telling now?! now?!", variables: [] },
  { text: "Scene mottha maari hoytu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "whole scene changed!", variables: [] },
  { text: "Devru! Idu heg possible!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "God! how is this possible!", variables: [] },
  { text: "Ivshtu dodda idda?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "this big?!", variables: [] },
  { text: "Idu {object} alla?! Nijavaaddu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is a {object}?! real one!", variables: ["{object}"] },
  { text: "Prana hogthide shock inda!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "dying from shock!", variables: [] },
  { text: "Enna timing guru!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what timing!", variables: [] },
  { text: "Yella okkosari aybitta!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything happened at once!", variables: [] },
  { text: "Money! Thumpa money!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "money! lots of money!", variables: [] },
  { text: "Record break aytu guru!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "record broken!", variables: [] },
  { text: "Idi miracle guru! Pure miracle!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "miracle!", variables: [] },
  { text: "Obba kooda helilla guru!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "nobody even told me!", variables: [] },
  { text: "Saththa hogthivi ansutte!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "feels like we'll die!", variables: [] },
  { text: "Enna madodu ippa?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what to do now?!", variables: [] },
  { text: "Inda idu hegbantu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "how did this come from here?!", variables: [] },
  { text: "Yella mugdibitta! Sarvanaasha!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "everything ended! disaster!", variables: [] },
  { text: "Wait! Idu adu alla!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "wait! this isn't that!", variables: [] },
  { text: "Arey baapre!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh my!", variables: [] },
  { text: "Tumba channaagide! Super!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "very nice! super!", variables: [] },
  { text: "Huchchu guru! Full huchchu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "crazy! fully crazy!", variables: [] },
  { text: "Ninn phone yelli?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "where's your phone?!", variables: [] },
  { text: "Vera level content guru!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "another level!", variables: [] },
  { text: "Timing mugdibitta already!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "time's up already!", variables: [] },
  { text: "Adhbhutha guru! Pura adhbhutha!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "wonderful! pure wonder!", variables: [] },
  { text: "Heg helodu?! Yen helodu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "how to tell?! what to tell?!", variables: [] },
  { text: "Sariyaagi keli?! Ondhe sala helbthini!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "heard right?! saying only once!", variables: [] },

  // ANGER (45)
  { text: "Saku! Nimda aaytu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "enough! had enough of you!", variables: [] },
  { text: "Baai muccko!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "shut your mouth!", variables: [] },
  { text: "Ninage sense illa?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't you have sense?!", variables: [] },
  { text: "Ninna nodi kooda agalla!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "can't even look at you!", variables: [] },
  { text: "Idu last warning!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "this is the last warning!", variables: [] },
  { text: "Hogappa! Nanna munde barberda!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "go! don't come before me!", variables: [] },
  { text: "Ninna yinda ella kedu aytu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "everything ruined because of you!", variables: [] },
  { text: "Yaavaglu idhe thappu!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "always the same mistake!", variables: [] },
  { text: "Nambike kaledu hogoytu!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "trust is lost!", variables: [] },
  { text: "Innondu mathu aadidrye...", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "if you say one more word...", variables: [] },
  { text: "Limit cross maadbitta!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "crossed the limit!", variables: [] },
  { text: "Nann helida kelthilla?!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "didn't listen to what I said?!", variables: [] },
  { text: "Drohaa! Dodda drohaa!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "betrayal! big betrayal!", variables: [] },
  { text: "Naatka madberda!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't do drama!", variables: [] },
  { text: "Ninage naachu ilva?!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "aren't you ashamed?!", variables: [] },
  { text: "Idu tappu! Dodda tappu!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "this is wrong! big mistake!", variables: [] },
  { text: "Onthara maadberda!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't annoy me!", variables: [] },
  { text: "Ninna tricks ella illi kelsa agolla!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "your tricks won't work here!", variables: [] },
  { text: "Ninage yaaru helide idu madodu?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "who told you to do this?!", variables: [] },
  { text: "Hogu! Ninna beku illa!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "go! I don't need you!", variables: [] },
  { text: "Nann kshamise madolla!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I won't forgive!", variables: [] },
  { text: "Munde barberda!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't come forward!", variables: [] },
  { text: "Nanna patience test madberda!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't test my patience!", variables: [] },
  { text: "Enough guru! Enough!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "enough!", variables: [] },
  { text: "Nann heldini tagolodu keliskolilla!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "you don't follow what I say!", variables: [] },
  { text: "Yelli idde innu?! Bega baa!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "where are you still?! come fast!", variables: [] },
  { text: "Control maadkoa guru!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "control yourself!", variables: [] },
  { text: "Summane iru! Summane!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "stay quiet! quiet!", variables: [] },
  { text: "Nanage gothillva ninna?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't I know you?!", variables: [] },
  { text: "Blood boil agthide nanna!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "my blood is boiling!", variables: [] },
  { text: "Munde nodkothini!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "I'll see about this later!", variables: [] },
  { text: "Ella ninna yinda!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "all because of you!", variables: [] },
  { text: "Innondsala maadidre...", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "if you do it one more time...", variables: [] },
  { text: "Maneli helbthini!", emotion: "anger", intensity: "medium", gender: "any", archetype: "child", context: "I'll tell at home!", variables: [] },
  { text: "Ninna mela koppa barthidde guru!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "anger building against you!", variables: [] },
  { text: "Haagella maadbardu!", emotion: "anger", intensity: "medium", gender: "any", archetype: "elder", context: "shouldn't do things like that!", variables: [] },
  { text: "Nanna enna andkondidya?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "what do you think I am?!", variables: [] },
  { text: "Heli heli! Enu maadidya?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "tell me! what did you do?!", variables: [] },
  { text: "Yaavaaga maaridya?!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "will you ever change?!", variables: [] },
  { text: "Nanna thuni idzilla yaarige!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't mess with me!", variables: [] },
  { text: "Vayassu agutte kaani buddhi barolla!", emotion: "anger", intensity: "medium", gender: "any", archetype: "elder", context: "you grow older but not wiser!", variables: [] },
  { text: "Bokka! Dodda bokka maadbitta!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "blunder! big blunder!", variables: [] },
  { text: "Naan yaaru gothilla ninage?!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "don't you know who I am?!", variables: [] },
  { text: "Ninna jothege mathadodu vyartha!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "talking to you is useless!", variables: [] },
  { text: "Patience guru! Yeshtu patience hadli?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "how much patience!", variables: [] },

  // FEAR (35)
  { text: "Amma! Bhaya agthide!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "mom! I'm scared!", variables: [] },
  { text: "Deyva! Kaapadu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "God! save us!", variables: [] },
  { text: "Bhoota! Oodona!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "ghost! let's run!", variables: [] },
  { text: "Nanage tumba bhaya agthide!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "I'm very scared!", variables: [] },
  { text: "Alli nodberda! Alli enu ide!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look there!", variables: [] },
  { text: "Oodona! Bega!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "let's run! fast!", variables: [] },
  { text: "Yaaru iddare alli?!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "who's there?!", variables: [] },
  { text: "Kaalu nadugthide bhaya inda!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "legs trembling from fear!", variables: [] },
  { text: "Illinda hogoraa! Bega!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "let's leave! fast!", variables: [] },
  { text: "Hindhakke nodberda! Oodu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look back! run!", variables: [] },
  { text: "Haavu! Haavu idde!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "snake! there's a snake!", variables: [] },
  { text: "Manege hogoraa! Ippa!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "let's go home! now!", variables: [] },
  { text: "Adu barthide! Adu barthide!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's coming!", variables: [] },
  { text: "Bekkondko! Bega!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "hide! quickly!", variables: [] },
  { text: "Illi obbanay irake agolla!", emotion: "fear", intensity: "medium", gender: "any", archetype: "child", context: "can't stay alone here!", variables: [] },
  { text: "Kai hidko guru!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "hold my hand!", variables: [] },
  { text: "Light hogoytu! Kaadu aytu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "lights went out! dark!", variables: [] },
  { text: "Enu shabda adu?!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "what sound was that?!", variables: [] },
  { text: "Help! Yaradru banni!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "help! someone come!", variables: [] },
  { text: "Shhh! Shabda madberda! Kelsthade!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "shh! don't make noise! it'll hear!", variables: [] },
  { text: "Idu trap guru! Sikkbitta!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's a trap! caught!", variables: [] },
  { text: "Horatana daari illa!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "no way out!", variables: [] },
  { text: "Bhayapadberda! Naan iddini!", emotion: "fear", intensity: "medium", gender: "any", archetype: "hero", context: "don't be afraid! I'm here!", variables: [] },
  { text: "Illi enu sari illa!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "something isn't right here!", variables: [] },
  { text: "Adu nanna kadege nodthide!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's looking at me!", variables: [] },
  { text: "Kaadolagey hogberda!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't go into the forest!", variables: [] },
  { text: "Baaglu moocchi! Bega!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "close the door! quickly!", variables: [] },
  { text: "Raatri enu aaguthdo!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "what will happen at night!", variables: [] },
  { text: "Naanu noddini! Nijava!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "I saw it! really!", variables: [] },
  { text: "Adu monster guru! Dodda monster!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "it's a monster! big one!", variables: [] },
  { text: "Praana hogthide bhaya inda!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "dying from fear!", variables: [] },
  { text: "Kaalu edoke agalla bhayada!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "can't lift feet from fear!", variables: [] },
  { text: "Nanna hinde yaaro nintirade!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "someone behind me!", variables: [] },
  { text: "Light thago! Enu kanisthilla!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "bring light! can't see!", variables: [] },
  { text: "Idu shaapitha jagah guru!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "this place is cursed!", variables: [] },

  // HAPPINESS (45)
  { text: "Tumba channaagide! Super!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "very nice! super!", variables: [] },
  { text: "Geddbitta! Namma team geddtu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "won! our team won!", variables: [] },
  { text: "Aaha! Idu tane nija santhosa!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "this is true happiness!", variables: [] },
  { text: "Party time guru! Celebration!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "party time!", variables: [] },
  { text: "Aaytu! Maadbitta!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "done! did it!", variables: [] },
  { text: "Tumba chenaagi maadidira!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "you did very well!", variables: [] },
  { text: "Kanasu nija aytu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "dream came true!", variables: [] },
  { text: "Laddu hanchona! Santhosa!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "distribute laddus!", variables: [] },
  { text: "Neenu genius guru!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're a genius!", variables: [] },
  { text: "Best day ever guru!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "best day ever!", variables: [] },
  { text: "Nanna kashta phalanitu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "hero", context: "my hard work paid off!", variables: [] },
  { text: "Devrige dhanyavaada!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "thanks to God!", variables: [] },
  { text: "Full marks! Full marks bantu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "got full marks!", variables: [] },
  { text: "{name}! Neenu tumba great guru!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're very great!", variables: ["{name}"] },
  { text: "Idu winning moment guru!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "winning moment!", variables: [] },
  { text: "Yellargu thanks helpiddakke!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "thanks to all!", variables: [] },
  { text: "Tumba olleya dina idu!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "very good day!", variables: [] },
  { text: "Namma team number one!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "our team number one!", variables: [] },
  { text: "Santhoshda kanniru barthide!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "tears of joy!", variables: [] },
  { text: "Nodu nodu! Navu maadbitta!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "look! we did it!", variables: [] },
  { text: "Ice cream tindona! Celebrate!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "let's eat ice cream!", variables: [] },
  { text: "Manege hogi helbthini!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "going home to tell!", variables: [] },
  { text: "Amma! Naan pass aaythe!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "mom! I passed!", variables: [] },
  { text: "Idu teamwork guru! Pure teamwork!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "teamwork!", variables: [] },
  { text: "Records break maadbitta!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "broke records!", variables: [] },
  { text: "Champion! Neenu champion guru!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "you're a champion!", variables: [] },
  { text: "Miracle guru! Pure miracle!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "miracle!", variables: [] },
  { text: "Biryani tindona! Nanna treat!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "biryani! my treat!", variables: [] },
  { text: "Mass guru! Standing ovation!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "mass! standing ovation!", variables: [] },
  { text: "Yellaru heroes!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "everyone's heroes!", variables: [] },
  { text: "Kashta aadru worth it guru!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "tough but worth it!", variables: [] },
  { text: "Golden moment!", emotion: "happiness", intensity: "high", gender: "any", archetype: "narrator", context: "golden moment!", variables: [] },
  { text: "Hip hip hurray!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "hip hip hooray!", variables: [] },
  { text: "Vera level scene guru!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "another level!", variables: [] },
  { text: "Cinema tara aytu life!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "life's like a movie!", variables: [] },
  { text: "Ennoda prarthana kelithu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "my prayer was heard!", variables: [] },
  { text: "Dance maadona! Special day!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "let's dance!", variables: [] },
  { text: "Prashasthi! Namma prashasthi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "award! our award!", variables: [] },
  { text: "Baga maadidya {name}! Proud of you!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "well done!", variables: ["{name}"] },
  { text: "Inimel ella maaruthe!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "everything changes from now!", variables: [] },
  { text: "Number 1 navu! Number 1!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "we're number 1!", variables: [] },
  { text: "Ellru banni! Group photo!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "everyone come! group photo!", variables: [] },
  { text: "Special occasion guru!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "special occasion!", variables: [] },
  { text: "Jai Karnataka!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "victory chant!", variables: [] },
  { text: "Best news guru! Best news!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "best news!", variables: [] },

  // THINKING (30) + NARRATION (25) + MORAL (25) + CATCHPHRASE + FILLER + OTHER (~105)
  // THINKING
  { text: "Hmm... yochne madbekku!", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "must think!", variables: [] },
  { text: "Nanage ond idea barthide!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "I'm getting an idea!", variables: [] },
  { text: "Aagu aagu... arthaagthide!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "wait, understanding!", variables: [] },
  { text: "Adara artha enu andre...", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "its meaning is...", variables: [] },
  { text: "Navu haage maadiddre?", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "what if we do this?", variables: [] },
  { text: "Nanage ond plan idde!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "hero", context: "I have a plan!", variables: [] },
  { text: "Brain use maadu guru! Brain!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "use your brain!", variables: [] },
  { text: "Aa! Ippa arthaaytu!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "ah! now I understand!", variables: [] },
  { text: "Bere angle inda nodona!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "let's look from another angle!", variables: [] },
  { text: "Tappu inda kalthukkona!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "let's learn from mistakes!", variables: [] },
  { text: "Ninage enu anisthide?", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "what do you think?", variables: [] },
  { text: "Naanu yochne madthiddini...", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "I'm thinking...", variables: [] },
  { text: "Answer tumba simple!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "answer is simple!", variables: [] },
  { text: "Problem iddre solution nu irthade!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "if problem then solution too!", variables: [] },
  { text: "Wait wait wait! Eureka!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "eureka!", variables: [] },
  { text: "Practice inda ella saadya!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "everything possible with practice!", variables: [] },
  { text: "Idu clue guru! Definite clue!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "this is a clue!", variables: [] },
  { text: "Ippa bulb on aaytu!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "the bulb turned on!", variables: [] },
  { text: "Yellrige helona! Daari siktu!", emotion: "thinking", intensity: "high", gender: "any", archetype: "hero", context: "tell everyone! found the way!", variables: [] },
  { text: "Idu pattern guru! Nodthiddiya?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "this is a pattern! see?", variables: [] },
  { text: "Ippa arthaaytha?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "now you understand?", variables: [] },
  { text: "Taalmey! Taalmey!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "patience!", variables: [] },
  { text: "Utthara ninna hatthira ide!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "the answer is with you!", variables: [] },
  { text: "Mundhu prashne arthamaasko!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "first understand the question!", variables: [] },
  { text: "Idu miss maadbitta! Important!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "we missed this!", variables: [] },
  { text: "Hmmm... interesting... tumba interesting!", emotion: "thinking", intensity: "low", gender: "any", archetype: "villain", context: "villain interest", variables: [] },
  { text: "Yelli tappu aaytu? Nodona!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "where was the mistake?", variables: [] },
  { text: "Step by step maadona!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "step by step!", variables: [] },
  { text: "Neenu ninage kinta jaasti capable!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "you're more capable than you think!", variables: [] },
  { text: "Zyaasti yochanney madberda! Action tago!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "hero", context: "don't overthink! take action!", variables: [] },
  // NARRATION
  { text: "Amele enu aaytu? Kelona!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "what happened next? listen!", variables: [] },
  { text: "Thumba hoinda...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "long long ago...", variables: [] },
  { text: "Ippa mundina kathe kelona!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "let's hear next story!", variables: [] },
  { text: "Ond ooru alli ond {object} ittu...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "in a village there was a...", variables: ["{object}"] },
  { text: "Aadre kathe illi mugiyolla!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "story doesn't end here!", variables: [] },
  { text: "Nodona enu aaguthe!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "let's see what happens!", variables: [] },
  { text: "Ippa nija kathe start!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "real story starts now!", variables: [] },
  { text: "Kelavu ganTe haamele...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "after a few hours...", variables: [] },
  { text: "Maruholdhu beligge...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "next day morning...", variables: [] },
  { text: "Haage ond hosa adventure start aaytu!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "thus new adventure started!", variables: [] },
  { text: "Yellru andkondru mugidibitta antha... aadre!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everyone thought over... but!", variables: [] },
  { text: "{name} maadthaara? Nodona!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "can they do it? let's see!", variables: ["{name}"] },
  { text: "Aaga yaaru nirekshe maadada vishaya aaytu!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "then unexpected thing happened!", variables: [] },
  { text: "Aaga... suddenly...", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "then... suddenly...", variables: [] },
  { text: "Ella badlaagthide!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everything's changing!", variables: [] },
  { text: "Katheli innondu twist!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "another twist!", variables: [] },
  { text: "Final round! Kodaneya avasara!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "final round! last chance!", variables: [] },
  { text: "Idu trailer mathra! Picture innu ide!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "just the trailer!", variables: [] },
  { text: "Neravagi climax ge hogona!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "straight to climax!", variables: [] },
  { text: "Ee kathe nenapu ittkona!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "remember this story!", variables: [] },
  { text: "Ippa kathe mundey hogthide...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "story moves forward...", variables: [] },
  { text: "Kaala maaraythu... paristhiti maaraythu...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "times and situations changed...", variables: [] },
  { text: "Aadre nijvaglu ella sari aaytha?", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "but did everything really work out?", variables: [] },
  { text: "Idu hosa shuruvaathu!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "this is a new beginning!", variables: [] },
  { text: "Ondhu pakkada... innondhu pakkada...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "on one side... another side...", variables: [] },
  // MORAL
  { text: "Adakkay helthare... kashta madidre phala sigthade!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "hard work brings results!", variables: [] },
  { text: "Paatha enu andre... sullu helabaradu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "lesson: don't lie!", variables: [] },
  { text: "Makklare! Ivattu enu kalthkondvi?", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "kids! what did we learn?", variables: [] },
  { text: "Satya yavaglu gelluthe!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "truth always wins!", variables: [] },
  { text: "Geleaythana tane dodda bala!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "friendship is strength!", variables: [] },
  { text: "Dhairya bittkobaradu yavaglu!", emotion: "moral", intensity: "high", gender: "any", archetype: "mentor", context: "never lose courage!", variables: [] },
  { text: "Dhodavru helddu keli!", emotion: "moral", intensity: "low", gender: "any", archetype: "elder", context: "listen to elders!", variables: [] },
  { text: "Aaathura gaada aagbaradu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "don't be in a hurry!", variables: [] },
  { text: "Ondu aadre bala!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "unity is strength!", variables: [] },
  { text: "Aase kettu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "greed is bad!", variables: [] },
  { text: "Kashta kaalada alli nija gelaeyaru goththaguthe!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "true friends show in hard times!", variables: [] },
  { text: "Bereyavarige sahaya maadidre... namage kooda barthade!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "help others and help comes!", variables: [] },
  { text: "Bhayada hinde geluvide!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "victory behind fear!", variables: [] },
  { text: "Tappu oppkobeku dhairya beku!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "admitting mistakes needs courage!", variables: [] },
  { text: "Vidyege vayasu illa!", emotion: "moral", intensity: "low", gender: "any", archetype: "mentor", context: "no age for learning!", variables: [] },
  { text: "Seriyaagi maadidre ella saadya!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "together everything possible!", variables: [] },
  { text: "Ee paatha nenapu ittkona!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "remember this lesson!", variables: [] },
  { text: "Kalithkothira iru! Yavaglu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "keep learning! always!", variables: [] },
  { text: "Nijavaaddu mathaadona!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "speak the truth!", variables: [] },
  { text: "Shortcuts kelsa agolla life alli!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "shortcuts don't work!", variables: [] },
  { text: "Yaaranu chikka antha thilberda!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "don't underestimate anyone!", variables: [] },
  { text: "Bittkodevaru yavaglu gelolla!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "quitters never win!", variables: [] },
  { text: "Olledu maadidre olledu barthade!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "do good get good!", variables: [] },
  { text: "Mundina episode alli innu kaltkoona! Bye!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "more in next episode!", variables: [] },
  { text: "Ee kathe ishtavaadre... share madi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "if you liked it share!", variables: [] },
  // CATCHPHRASES + FILLERS (30)
  { text: "Nanna hesru {name}! Naan yavaglu ready!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "hero intro", variables: ["{name}"] },
  { text: "Idu nanna specialty!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "my specialty!", variables: [] },
  { text: "Parvaagilla! Innond sala try maadona!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "let's try again!", variables: [] },
  { text: "Mundhu oota! Baki ella amele!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "food first!", variables: [] },
  { text: "Mission start!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "mission start!", variables: [] },
  { text: "Power up!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "power up!", variables: [] },
  { text: "Game over villains!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "game over!", variables: [] },
  { text: "Naanu vapas barthini!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "I will return!", variables: [] },
  { text: "Naan haar accept maadolla!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "won't accept defeat!", variables: [] },
  { text: "Oota yelli?!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "where's food?!", variables: [] },
  { text: "Tension tagolberda!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "don't take tension!", variables: [] },
  { text: "Sari sari!", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "okay okay!", variables: [] },
  { text: "Helu guru!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "tell me!", variables: [] },
  { text: "Aagu aagu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "wait!", variables: [] },
  { text: "Adu alla...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "that's not it...", variables: [] },
  { text: "Nodu nodu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "look!", variables: [] },
  { text: "Kelu kelu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "listen!", variables: [] },
  { text: "Howdu howdu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "yes yes!", variables: [] },
  { text: "Illa illa!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "no no!", variables: [] },
  { text: "Baa!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "come!", variables: [] },
  { text: "Hogu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "go!", variables: [] },
  { text: "Ond nimsha!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "one moment!", variables: [] },
  { text: "Gothide gothide!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "I know!", variables: [] },
  { text: "Simple guru!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "simple!", variables: [] },
  { text: "Done guru!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "done!", variables: [] },
  { text: "Ready ah?", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "ready?", variables: [] },
  // ENCOURAGEMENT + DETERMINATION + WARNING + GRATITUDE + CELEBRATION (25)
  { text: "Ninage aaguthe guru!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "you can do it!", variables: [] },
  { text: "Dhairya bittkobaradu!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "don't lose courage!", variables: [] },
  { text: "Innond sala try maadu!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "try once more!", variables: [] },
  { text: "Naanu ninna jothey iddini!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "friend", context: "I'm with you!", variables: [] },
  { text: "Chennaagi maaddidya! Innu chennagi maadu!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "did well! do better!", variables: [] },
  { text: "Geluvu hathira ide guru!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "victory is near!", variables: [] },
  { text: "Shabash guru!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "elder", context: "well done!", variables: [] },
  { text: "Navu yellru ninna jothey iddivi!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "friend", context: "we're all with you!", variables: [] },
  { text: "Ippa agbaaradu!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "can't stop now!", variables: [] },
  { text: "Naanu maadi thorsthini!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "I'll prove it!", variables: [] },
  { text: "Enu aadru sarey!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "no matter what!", variables: [] },
  { text: "Idu nanna promise!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "my promise!", variables: [] },
  { text: "Jagrathey! Apaya!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "careful! danger!", variables: [] },
  { text: "Alli hogberda! Dangerous!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "don't go there!", variables: [] },
  { text: "Mugiberda! Visha ide!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "don't touch! poison!", variables: [] },
  { text: "Last warning idu guru!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "last warning!", variables: [] },
  { text: "Thanks guru! Tumba help aaytu!", emotion: "gratitude", intensity: "medium", gender: "any", archetype: "any", context: "thanks! big help!", variables: [] },
  { text: "Dhanyavaada! Hrudayapoorvaka!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "heartfelt thanks!", variables: [] },
  { text: "Neenu illde naan illa!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "without you I'm nothing!", variables: [] },
  { text: "{name}! Neenu best friend guru!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "friend", context: "best friend!", variables: ["{name}"] },
  { text: "Party time guru! Celebration!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "party!", variables: [] },
  { text: "Geddbitta! Champions!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "won! champions!", variables: [] },
  { text: "Badhaai! Badhaai!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "congratulations!", variables: [] },
  { text: "Hip hip hurray!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "hooray!", variables: [] },
  { text: "Number 1! Navu number 1!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "we're number 1!", variables: [] },
];

export const kannadaBank: DialogueBank = {
  language: 'kannada',
  isoCode: 'kn-IN',
  displayName: 'Kannada',
  lines,
};
