/**
 * Expert 5: Bharat Jadhav Style — Marathi Comedy Dialogue Bank
 * 500+ natural Marathi dialogues with Mumbai/Pune colloquial slang.
 */

import { DialogueBank, DialogueLine } from './types';

const lines: DialogueLine[] = [
  // GREETINGS (50)
  { text: "Kay re! Kasa aahe?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "casual greeting", variables: [] },
  { text: "Namaskar! Kase aahat?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "respectful greeting", variables: [] },
  { text: "Bhari! Kiti divas zale!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "how many days!", variables: [] },
  { text: "Ekdum jhakkas! Tu aayla!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "great! you came!", variables: [] },
  { text: "Ye re! Ithe ye! Bas!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "come! sit!", variables: [] },
  { text: "Ho na! Aahe na?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "Pune style greeting", variables: [] },
  { text: "Mast! Tu aalas tar party!", emotion: "greeting", intensity: "high", gender: "male", archetype: "friend", context: "you came means party!", variables: [] },
  { text: "Kashala re! Kuthe hotas?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "why! where were you?", variables: [] },
  { text: "Guruji! Pranam!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "teacher! greetings!", variables: [] },
  { text: "Aai! Aali ga!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "child", context: "mom! came!", variables: [] },
  { text: "Baba! Ithe bagh!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "child", context: "dad! look here!", variables: [] },
  { text: "VIP aalay! Welcome!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "VIP has arrived!", variables: [] },
  { text: "Good morning saheb!", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "morning greeting", variables: [] },
  { text: "Dada! Kasa kay?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "brother! how's it?", variables: [] },
  { text: "Taai! Kashi aahat?", emotion: "greeting", intensity: "low", gender: "female", archetype: "any", context: "sister! how are you?", variables: [] },
  { text: "Boss! Enu scene?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "boss! what scene?", variables: [] },
  { text: "Ya ya! Infun ye!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "come come! come in!", variables: [] },
  { text: "Arre {name}! Tu ithe!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "you're here!", variables: ["{name}"] },
  { text: "Macha! Ready aahe ka?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! ready?", variables: [] },
  { text: "Kaka! Namaskar!", emotion: "greeting", intensity: "low", gender: "male", archetype: "child", context: "uncle! greetings!", variables: [] },
  { text: "Mami! Ya na!", emotion: "greeting", intensity: "medium", gender: "female", archetype: "any", context: "aunt! come!", variables: [] },
  { text: "Arre! Zinda aahe ki nahi?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "are you alive?", variables: [] },
  { text: "Mass entry re!", emotion: "greeting", intensity: "high", gender: "male", archetype: "hero", context: "mass entry!", variables: [] },
  { text: "Chala! Shuru karu!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "let's start!", variables: [] },
  { text: "Ajji! Aashirvad dya!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "grandma! bless me!", variables: [] },
  { text: "Hello hello! Testing!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "dramatic greeting", variables: [] },
  { text: "Bhai! Kiti divas zale bhetu nahi!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! so many days no meeting!", variables: [] },
  { text: "Aamcha area la swagat!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "welcome to our area!", variables: [] },
  { text: "Ya! Chaaha ghe!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "come! have tea!", variables: [] },
  { text: "Porga! Ithe ye!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "elder", context: "boy! come here!", variables: [] },
  { text: "Porgi! Ye ga!", emotion: "greeting", intensity: "medium", gender: "female", archetype: "elder", context: "girl! come!", variables: [] },
  { text: "Bhau! Namaskar!", emotion: "greeting", intensity: "low", gender: "male", archetype: "any", context: "brother! greetings!", variables: [] },
  { text: "Mi aaloy! Party start kara!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "I'm here! start party!", variables: [] },
  { text: "Super! Tu aalas mhanun!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "super! because you came!", variables: [] },
  { text: "Nanna! Kasa aahes?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "brother! how are you?", variables: [] },
  { text: "Wahini! Kashi aahat?", emotion: "greeting", intensity: "low", gender: "female", archetype: "any", context: "sister-in-law! how are you?", variables: [] },
  { text: "Late ka aalas re?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "why late?", variables: [] },
  { text: "Tu nahitas tar gammat nahi!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "no fun without you!", variables: [] },
  { text: "Aaychya! Tu ithe?!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "you here?! (surprise)", variables: [] },
  { text: "Group photo gheu ya! Sagla ya!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "group photo! everyone come!", variables: [] },
  { text: "Bro! What's up re?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "Maranglish greeting", variables: [] },
  { text: "Kaku! Ya na!", emotion: "greeting", intensity: "medium", gender: "female", archetype: "elder", context: "auntie! come!", variables: [] },
  { text: "Sagla ready? Chala!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "all ready? let's go!", variables: [] },
  { text: "Arre miss kela tula!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "missed you!", variables: [] },
  { text: "Aajoba! Pranaam!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "grandpa! greetings!", variables: [] },
  { text: "Wahh! Sagla aalay!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "wow! everyone's here!", variables: [] },
  { text: "Aamhi aalo! Scene start kara!", emotion: "greeting", intensity: "high", gender: "any", archetype: "hero", context: "we've arrived! start scene!", variables: [] },
  { text: "Suprabhat mitranno!", emotion: "greeting", intensity: "low", gender: "any", archetype: "narrator", context: "good morning friends!", variables: [] },
  { text: "Namaskar saheb!", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "greetings sir!", variables: [] },
  { text: "Ya re {name}! Bheta zala!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "finally met!", variables: ["{name}"] },

  // SURPRISE (45)
  { text: "Aai shapath! He kaay!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh my! what!", variables: [] },
  { text: "Bapre bap! Kaay zala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what happened!", variables: [] },
  { text: "Lay bhari! He kharach?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "awesome! really?!", variables: [] },
  { text: "Arre! Nahi nahi! He shakya nahi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "no! not possible!", variables: [] },
  { text: "He sach aahe ka?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "is this true?!", variables: [] },
  { text: "Kahich samjat nahi!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "don't understand anything!", variables: [] },
  { text: "Shock zala! Full shock!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "shocked!", variables: [] },
  { text: "Plan faltush zala! Mottha plan!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "plan flopped! whole plan!", variables: [] },
  { text: "Kauni kela he?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "who did this?!", variables: [] },
  { text: "Khara sangtos! Dolyanvar vishvas nahi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "seriously! can't believe my eyes!", variables: [] },
  { text: "He twist aahe re! Motha twist!", emotion: "surprise", intensity: "high", gender: "any", archetype: "narrator", context: "this is a twist!", variables: [] },
  { text: "Kashala? Kevha? Kasa?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "why? when? how?!", variables: [] },
  { text: "Swapna nahi na he?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "this isn't a dream right?!", variables: [] },
  { text: "Arre {name}! Tu he kelas?! Nammbavach nahi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "{name} did this?! unbelievable!", variables: ["{name}"] },
  { text: "Jackpot re! Full jackpot!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "jackpot!", variables: [] },
  { text: "Secret ughada zala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "secret exposed!", variables: [] },
  { text: "Aaichya! Dokyala chakkra yetoy!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "head is spinning!", variables: [] },
  { text: "He impossible aahe!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "impossible!", variables: [] },
  { text: "Atta sangtosh?! Atta?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "telling me now?! now?!", variables: [] },
  { text: "Sagla badlala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything changed!", variables: [] },
  { text: "Aai! Bagh he!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "mom! look!", variables: [] },
  { text: "Paise! Khup paise!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "money! lots!", variables: [] },
  { text: "Record todla re!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "record broken!", variables: [] },
  { text: "He miracle aahe! Pure miracle!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "miracle!", variables: [] },
  { text: "Light geli! Andhaar zala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "power went! dark!", variables: [] },
  { text: "He {object} aahe! Kharach!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is a real {object}!", variables: ["{object}"] },
  { text: "Mottha scene badlala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "whole scene changed!", variables: [] },
  { text: "Atta kaay karaycha?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what to do now?!", variables: [] },
  { text: "History re he! History!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "history!", variables: [] },
  { text: "Timing bagh! Exact aala!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what timing!", variables: [] },
  { text: "Sagla eka velela zhala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything at once!", variables: [] },
  { text: "Konich sangitla nahi re!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "nobody told me!", variables: [] },
  { text: "Mela maryach re!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "we're dead!", variables: [] },
  { text: "Mottha bokka zala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "big blunder!", variables: [] },
  { text: "Vera level content re!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "another level!", variables: [] },
  { text: "Ek minute! He te nahi!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "wait! this isn't that!", variables: [] },
  { text: "Devaa! He kasa shakya!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "God! how is this possible!", variables: [] },
  { text: "Arre baapre!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh my!", variables: [] },
  { text: "Kharach? Kharach kharach?", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "really? really really?", variables: [] },
  { text: "Tumba bhari!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "too good!", variables: [] },
  { text: "Sangaych tar sang! Kaay zhala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "if you must tell, tell! what happened!", variables: [] },
  { text: "Arre wah! He tar champion!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "wow! this is champion!", variables: [] },
  { text: "Thambha! Kaay sangtoy tu?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "wait! what are you saying?!", variables: [] },
  { text: "Ashakya re! Ashakya!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "impossible!", variables: [] },
  { text: "Sagla sampala! Sagla!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "everything's over!", variables: [] },

  // ANGER (40)
  { text: "Pureshay zala!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "enough!", variables: [] },
  { text: "Tond band kar!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "shut your mouth!", variables: [] },
  { text: "Tula akal aahe ki nahi?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "do you have brains?!", variables: [] },
  { text: "Tuzya mule he zala!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "this happened because of you!", variables: [] },
  { text: "Vishwas gela!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "trust is gone!", variables: [] },
  { text: "Aadhich sangitla hota!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "I told you earlier!", variables: [] },
  { text: "Natak band kar!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "stop the drama!", variables: [] },
  { text: "He shevtcha warning!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "last warning!", variables: [] },
  { text: "Chal nigh! Samor yeu nako!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "go! don't come before me!", variables: [] },
  { text: "Laaz nahi vatli?!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "aren't you ashamed?!", variables: [] },
  { text: "Limit zalay atta!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "limit crossed!", variables: [] },
  { text: "Tu kadhi sudharnaar?!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "when will you improve?!", variables: [] },
  { text: "He chukicha aahe! Mothi chuk!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "mistake! big mistake!", variables: [] },
  { text: "Dhokha! Motha dhokha!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "betrayal!", variables: [] },
  { text: "Tuzha tricks ithey chalnar nahi!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "your tricks won't work here!", variables: [] },
  { text: "Majhya patience chi test ghenakos!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't test my patience!", variables: [] },
  { text: "Ja! Tuzhi garaj nahi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "go! don't need you!", variables: [] },
  { text: "Mi maaf karnar nahi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I won't forgive!", variables: [] },
  { text: "Gappa! Gappa bas!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "quiet! just quiet!", variables: [] },
  { text: "Blood boil hotoy mazha!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "my blood is boiling!", variables: [] },
  { text: "Tula kaay vatla maazha?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "what do you think I am?!", variables: [] },
  { text: "Pudhe baghshil!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "you'll see later!", variables: [] },
  { text: "Enough re! Enough!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "enough!", variables: [] },
  { text: "Tuzhi saglya mule!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "all because of you!", variables: [] },
  { text: "Punha he kelash tar...", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "if you do this again...", variables: [] },
  { text: "Sangto re sangto! Kaay kelas?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "tell me! what did you do?!", variables: [] },
  { text: "Control kar swatala!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "control yourself!", variables: [] },
  { text: "Gharchi sang tula!", emotion: "anger", intensity: "medium", gender: "any", archetype: "child", context: "I'll tell at home!", variables: [] },
  { text: "Khup patience dakhavla mi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I showed too much patience!", variables: [] },
  { text: "Bokka! Motha bokka kelas!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "blunder! big blunder!", variables: [] },
  { text: "Tu mahit nahi mi kaun aahe!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "don't you know who I am?!", variables: [] },
  { text: "Tuzya barober bolne vyarth!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "talking to you is useless!", variables: [] },
  { text: "Punha same chuk?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "same mistake again?!", variables: [] },
  { text: "Majhya mula sangto tula!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I'm telling you from me!", variables: [] },
  { text: "Samor nako! Ja!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "not in front of me! go!", variables: [] },
  { text: "He galat! Khup galat!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "wrong! very wrong!", variables: [] },
  { text: "Tula kaay samjat nahi?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't you understand?!", variables: [] },
  { text: "Mazhi maaybhoon aahe! Nako tithey!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "this is my homeland!", variables: [] },
  { text: "Mala ekata sod!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "leave me alone!", variables: [] },
  { text: "He vichar kela hotas tu?!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "did you think about this?!", variables: [] },

  // FEAR (30)
  { text: "Aai! Bhiti vatay!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "mom! scary!", variables: [] },
  { text: "Bhoot! Pala re!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "ghost! run!", variables: [] },
  { text: "Devaa! Vaachav!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "God! save us!", variables: [] },
  { text: "Mala khup bhiti vatay!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "I'm very scared!", variables: [] },
  { text: "Tithe baghu nako! Tithe kaay aahe!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look there!", variables: [] },
  { text: "Palaa! Lavkar!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "run! fast!", variables: [] },
  { text: "Kaun aahe tithe?!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "who's there?!", variables: [] },
  { text: "Paay kaptat bhitine!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "legs shaking from fear!", variables: [] },
  { text: "Ithun nighuyaat! Lavkar!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "let's leave! fast!", variables: [] },
  { text: "Magey baghu nako! Pala!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look back! run!", variables: [] },
  { text: "Saap! Saap aahe!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "snake! there's a snake!", variables: [] },
  { text: "Gharla jaycha! Atach!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "go home! right now!", variables: [] },
  { text: "Te yetay! Te yetay!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's coming!", variables: [] },
  { text: "Lapa! Lavkar!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "hide! quickly!", variables: [] },
  { text: "Mi ekata raahu shakat nahi ithey!", emotion: "fear", intensity: "medium", gender: "any", archetype: "child", context: "can't stay alone here!", variables: [] },
  { text: "Haath dhar re!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "hold my hand!", variables: [] },
  { text: "Light geli! Andhaar!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "lights out! dark!", variables: [] },
  { text: "Kaay hota to aavaaz?!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "what was that sound?!", variables: [] },
  { text: "Help! Kauni tari ya!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "help! someone come!", variables: [] },
  { text: "Shhh! Aavaaz karu nako! Aikel!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "shh! it'll hear!", variables: [] },
  { text: "He saapla aahe! Aphsalo!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's a trap! caught!", variables: [] },
  { text: "Baher nigtaach nahi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "no way out!", variables: [] },
  { text: "Ghabarunako! Mi aahey!", emotion: "fear", intensity: "medium", gender: "any", archetype: "hero", context: "don't be scared! I'm here!", variables: [] },
  { text: "Te monster aahe! Motha monster!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "it's a monster!", variables: [] },
  { text: "Jiv gela bhitine!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "nearly died of fear!", variables: [] },
  { text: "Paay halat nahit bhitine!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "can't move feet!", variables: [] },
  { text: "Daar band kar! Lavkar!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "close the door! fast!", variables: [] },
  { text: "Mala kaahi tari disla! Kharach!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "I saw something! really!", variables: [] },
  { text: "Mazya magey kauni tar ubha aahe!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "someone behind me!", variables: [] },
  { text: "Light aana! Kaahi disat nahi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "bring light! can't see!", variables: [] },

  // HAPPINESS (40)
  { text: "Ekdum jhakkas! Mast!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "awesome!", variables: [] },
  { text: "Jinklo! Aamhi jinklo!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "we won!", variables: [] },
  { text: "Lay bhari! Tumhi great aahat!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "too good!", variables: [] },
  { text: "Party time re! Celebration!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "party time!", variables: [] },
  { text: "Zala! Aamhi kela!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "done! we did it!", variables: [] },
  { text: "Khup chhaan kela!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "did very well!", variables: [] },
  { text: "Swapna khara zala!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "dream came true!", variables: [] },
  { text: "Ladoo vaata! Aanand!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "distribute laddus!", variables: [] },
  { text: "Tu genius aahe re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're a genius!", variables: [] },
  { text: "Best day ever re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "best day!", variables: [] },
  { text: "Mazhi mehnat falali!", emotion: "happiness", intensity: "high", gender: "any", archetype: "hero", context: "my hard work paid off!", variables: [] },
  { text: "Devala dhanyavaad!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "thanks to God!", variables: [] },
  { text: "Full marks! Full marks aalay!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "got full marks!", variables: [] },
  { text: "{name}! Tu khup great aahe!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're great!", variables: ["{name}"] },
  { text: "Saglyanna thanks!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "thanks everyone!", variables: [] },
  { text: "Namma team number one!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "our team number one!", variables: [] },
  { text: "Aanandane dolyaat paani aalay!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "tears of joy!", variables: [] },
  { text: "Ice cream khauya! Celebrate!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "let's eat ice cream!", variables: [] },
  { text: "Gharla jaun sangto!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "going home to tell!", variables: [] },
  { text: "Aai! Mi pass zalo!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "mom! I passed!", variables: [] },
  { text: "He teamwork aahe! Pure teamwork!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "teamwork!", variables: [] },
  { text: "Records todla re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "broke records!", variables: [] },
  { text: "Champion! Tu champion aahe!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "champion!", variables: [] },
  { text: "He miracle aahe! Pure miracle!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "miracle!", variables: [] },
  { text: "Vada pav khauya! Mazhi treat!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "vada pav! my treat!", variables: [] },
  { text: "Mass re! Standing ovation!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "mass!", variables: [] },
  { text: "Sagla heroes aahat!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "all heroes!", variables: [] },
  { text: "Kathin hota pan worth it re!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "tough but worth it!", variables: [] },
  { text: "Golden moment!", emotion: "happiness", intensity: "high", gender: "any", archetype: "narrator", context: "golden moment!", variables: [] },
  { text: "Hip hip hurray!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "hooray!", variables: [] },
  { text: "Vera level scene re!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "another level!", variables: [] },
  { text: "Cinema saarkha zala life!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "life's like a movie!", variables: [] },
  { text: "Mazhi prarthana aikli!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "prayer heard!", variables: [] },
  { text: "Dance karuya! Special din!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "let's dance!", variables: [] },
  { text: "Bagh kela re {name}! Proud of you!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "well done!", variables: ["{name}"] },
  { text: "Aata sab kuch badalnar!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "everything changes now!", variables: [] },
  { text: "Number 1 aamhi! Number 1!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "number 1!", variables: [] },
  { text: "Jai Maharashtra!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "victory chant!", variables: [] },
  { text: "Best news re! Best news!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "best news!", variables: [] },
  { text: "Sagla ya! Group photo!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "group photo!", variables: [] },

  // THINKING (25) + NARRATION (25) + MORAL (25) + CATCHPHRASE + FILLER + OTHER (~220)
  { text: "Hmm... vichar karayला hava!", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "must think!", variables: [] },
  { text: "Mala ek idea yetoy!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "getting an idea!", variables: [] },
  { text: "Thamba thamba... samjlay!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "wait, understood!", variables: [] },
  { text: "Tyacha arth aahe ki...", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "its meaning is...", variables: [] },
  { text: "Mala ek plan aahe!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "hero", context: "I have a plan!", variables: [] },
  { text: "Brain vapar re! Brain!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "use your brain!", variables: [] },
  { text: "Aa! Atta samjla!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "now I understand!", variables: [] },
  { text: "Vegla angle ne bagh!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "look from different angle!", variables: [] },
  { text: "Chukitun shik!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "learn from mistakes!", variables: [] },
  { text: "Tula kaay vatata?", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "what do you think?", variables: [] },
  { text: "Answer khup simple aahe!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "answer is simple!", variables: [] },
  { text: "Problem aahe tar solution pan aahe!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "problem means solution too!", variables: [] },
  { text: "Wait wait wait! Eureka!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "eureka!", variables: [] },
  { text: "He clue aahe re! Nakkicha!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "this is a clue!", variables: [] },
  { text: "Atta bulb lagla!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "bulb lit up!", variables: [] },
  { text: "He pattern aahe! Disat ka?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "this is a pattern! see?", variables: [] },
  { text: "Atta samjla na?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "now you understand?", variables: [] },
  { text: "Saburi! Saburi!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "patience!", variables: [] },
  { text: "Practice ne sagla shakya!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "everything possible with practice!", variables: [] },
  { text: "Step by step karu!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "step by step!", variables: [] },
  { text: "Hmmm... interesting!", emotion: "thinking", intensity: "low", gender: "any", archetype: "villain", context: "villain interest", variables: [] },
  { text: "Kuthe chuk zhali? Baghu!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "where was the mistake?", variables: [] },
  { text: "Uttar tuzya kade aahe!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "answer is with you!", variables: [] },
  { text: "Aadhi prashna samjun ghe!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "first understand the question!", variables: [] },
  { text: "Jasta vichar karu nako! Action ghe!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "hero", context: "don't overthink! take action!", variables: [] },
  // NARRATION
  { text: "Mag kaay zhala? Aika!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "what happened next? listen!", variables: [] },
  { text: "Khup purvi...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "long ago...", variables: [] },
  { text: "Ata pudhlya goshticha aika!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "now listen to next story!", variables: [] },
  { text: "Ek gaavat ek {object} hota...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "in a village there was...", variables: ["{object}"] },
  { text: "Pan gosht itthe sampat nahi!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "story doesn't end here!", variables: [] },
  { text: "Baghuyaat kaay hota!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "let's see what happens!", variables: [] },
  { text: "Ata khari gosht shuru!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "real story starts!", variables: [] },
  { text: "Kahi taasannantar...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "after hours...", variables: [] },
  { text: "Dusrya divshi sakali...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "next day morning...", variables: [] },
  { text: "Asa ek nava adventure suroo zala!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "new adventure started!", variables: [] },
  { text: "Saglyana vatla sampla... pan!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everyone thought over... but!", variables: [] },
  { text: "Tevha kauni vichar na kela goshta zali!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "something unexpected happened!", variables: [] },
  { text: "Ani tevha... achanak...", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "and then... suddenly...", variables: [] },
  { text: "Sagla badalnar hota!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everything about to change!", variables: [] },
  { text: "Goshtit ajun ek twist!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "another twist!", variables: [] },
  { text: "Final round! Shevtchi sandhi!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "final round!", variables: [] },
  { text: "He trailer hota! Picture ajun aahe!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "just the trailer!", variables: [] },
  { text: "Hi gosht lakshaat theva!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "remember this story!", variables: [] },
  { text: "Ata gosht pudhe jate...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "story moves forward...", variables: [] },
  { text: "Kaal badlala... paristhiti badlali...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "times changed...", variables: [] },
  { text: "Pan kharach sagla theek zala ka?", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "did everything become okay?", variables: [] },
  { text: "He navi suruvaat!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "new beginning!", variables: [] },
  { text: "Ek baajula... dusrya baajula...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "one side... other side...", variables: [] },
  { text: "Seedha climax la jauya!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "straight to climax!", variables: [] },
  // MORAL
  { text: "Mhanun mhantat... mehnat karaychi tar phal milta!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "hard work pays!", variables: [] },
  { text: "Dhada kaay aahe... khoTe bolaycha nahi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "don't lie!", variables: [] },
  { text: "Mulanno! Aaj kaay shiklat?", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "kids! what did you learn?", variables: [] },
  { text: "Satya nehami jinkte!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "truth always wins!", variables: [] },
  { text: "Maitri mothi takat aahe!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "friendship is strength!", variables: [] },
  { text: "Dhairya kadhi sodaycha nahi!", emotion: "moral", intensity: "high", gender: "any", archetype: "mentor", context: "never lose courage!", variables: [] },
  { text: "Mothyancha aika!", emotion: "moral", intensity: "low", gender: "any", archetype: "elder", context: "listen to elders!", variables: [] },
  { text: "Ghaai ghaai madhe chuk hote!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "haste leads to mistakes!", variables: [] },
  { text: "Ekjut tar bal aahe!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "unity is strength!", variables: [] },
  { text: "Lobh vait aahe!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "greed is bad!", variables: [] },
  { text: "Kathin kalat khare mitra kaltat!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "true friends show in hard times!", variables: [] },
  { text: "Chuk manya karayला dhairya lagta!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "admitting mistakes needs courage!", variables: [] },
  { text: "Shiknyala vay nahi!", emotion: "moral", intensity: "low", gender: "any", archetype: "mentor", context: "no age for learning!", variables: [] },
  { text: "Milun kela tar sagla shakya!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "together everything possible!", variables: [] },
  { text: "Ha dhada lakhshaat theva!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "remember this lesson!", variables: [] },
  { text: "Shikta raha! Nehami!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "keep learning!", variables: [] },
  { text: "Kaahi zala tari khara bol!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "speak truth!", variables: [] },
  { text: "Life madhe shortcuts chalat nahi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "shortcuts don't work!", variables: [] },
  { text: "Konala laahan samju nako!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "don't underestimate!", variables: [] },
  { text: "Haratay to kadhi jinkat nahi!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "quitters never win!", variables: [] },
  { text: "Changla kela tar changla milta!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "do good get good!", variables: [] },
  { text: "Pudhlya episode madhe ajun shikuya! Bye!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "more next episode!", variables: [] },
  { text: "Hi gosht aavadli tar share kara!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "share if you liked!", variables: [] },
  { text: "Saburi cha phal god asta!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "patience bears sweet fruit!", variables: [] },
  { text: "Sapna bagha! Shikvat raha!", emotion: "moral", intensity: "high", gender: "any", archetype: "mentor", context: "chase dreams! keep learning!", variables: [] },
  // CATCHPHRASE + FILLER + OTHER (50)
  { text: "Mazha naav {name}! Mi nehami ready!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "hero intro", variables: ["{name}"] },
  { text: "He mazhi specialty aahe!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "my specialty!", variables: [] },
  { text: "Chalel! Punha try karu!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "let's try again!", variables: [] },
  { text: "Aadhi jevan! Baki nantar!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "food first!", variables: [] },
  { text: "Mission start!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "mission start!", variables: [] },
  { text: "Power up!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "power up!", variables: [] },
  { text: "Game over villains!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "game over!", variables: [] },
  { text: "Mi parat yein!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "I'll return!", variables: [] },
  { text: "Mi haar manyach nahi!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "won't accept defeat!", variables: [] },
  { text: "Jevan kuthe?!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "where's food?!", variables: [] },
  { text: "Tension nako ghe!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "don't take tension!", variables: [] },
  { text: "Bari bari!", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "okay okay!", variables: [] },
  { text: "Sang re!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "tell me!", variables: [] },
  { text: "Thamba thamba!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "wait!", variables: [] },
  { text: "Te nahi...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "not that...", variables: [] },
  { text: "Bagh bagh!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "look look!", variables: [] },
  { text: "Aik aik!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "listen!", variables: [] },
  { text: "Ho ho!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "yes yes!", variables: [] },
  { text: "Nahi nahi!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "no no!", variables: [] },
  { text: "Ya!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "come!", variables: [] },
  { text: "Ja!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "go!", variables: [] },
  { text: "Ek minute!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "one minute!", variables: [] },
  { text: "Mahitiye mahitiye!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "I know!", variables: [] },
  { text: "Simple re!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "simple!", variables: [] },
  { text: "Done!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "done!", variables: [] },
  { text: "Ready?", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "ready?", variables: [] },
  { text: "Tu kar shaktos!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "you can do it!", variables: [] },
  { text: "Dhairya sodu nako!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "don't lose courage!", variables: [] },
  { text: "Punha try kar!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "try again!", variables: [] },
  { text: "Mi tuzya barober aahey!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "friend", context: "I'm with you!", variables: [] },
  { text: "Jinkna javal aahe!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "victory is near!", variables: [] },
  { text: "Shabash re!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "elder", context: "well done!", variables: [] },
  { text: "Aamhi sagla tuzya barober!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "friend", context: "we're all with you!", variables: [] },
  { text: "Ata thaambaychya nahi!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "can't stop now!", variables: [] },
  { text: "Mi karun dakhvein!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "I'll prove it!", variables: [] },
  { text: "Kaahi zala tari!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "no matter what!", variables: [] },
  { text: "He mazha promise aahe!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "my promise!", variables: [] },
  { text: "Savdhan! Dhoka!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "careful! danger!", variables: [] },
  { text: "Tithe jau nako! Dhokadayak!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "don't go! dangerous!", variables: [] },
  { text: "He last warning aahe!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "last warning!", variables: [] },
  { text: "Thanks re! Khup madatilla!", emotion: "gratitude", intensity: "medium", gender: "any", archetype: "any", context: "thanks! big help!", variables: [] },
  { text: "Dhanyavaad! Manpoorvak!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "heartfelt thanks!", variables: [] },
  { text: "Tu nahitas tar mi nahito!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "without you I'm nothing!", variables: [] },
  { text: "{name}! Tu best friend aahe re!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "friend", context: "best friend!", variables: ["{name}"] },
  { text: "Party time re! Celebration!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "party!", variables: [] },
  { text: "Jinklo! Champions!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "won! champions!", variables: [] },
  { text: "Abhinandan! Abhinandan!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "congratulations!", variables: [] },
  { text: "Hip hip hurray!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "hooray!", variables: [] },
  { text: "Number 1! Aamhi number 1!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "number 1!", variables: [] },
  { text: "Trophy aamchi! Aamchi trophy!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "our trophy!", variables: [] },
];

export const marathiBank: DialogueBank = {
  language: 'marathi',
  isoCode: 'mr-IN',
  displayName: 'Marathi',
  lines,
};
