/**
 * Expert 3: Vadivelu Style — Tamil Comedy Dialogue Bank
 * 500+ natural Tamil dialogues with Chennai/street Tamil slang.
 */

import { DialogueBank, DialogueLine } from './types';

const lines: DialogueLine[] = [
  // ============================================================
  // GREETINGS (55)
  // ============================================================
  { text: "Dei! Eppadi irukka?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "casual male greeting", variables: [] },
  { text: "Vanakkam! Nalla irukkeenga?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "respectful greeting", variables: [] },
  { text: "Da! Enga pona?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "where did you go?", variables: [] },
  { text: "Dei dei dei! Yaaru vandhurukkaan paaru!", emotion: "greeting", intensity: "high", gender: "male", archetype: "any", context: "look who's come!", variables: [] },
  { text: "Machaan! Romba naala aachi!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! it's been long!", variables: [] },
  { text: "Vaa da! Vaa! Ukkaaru!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "come sit!", variables: [] },
  { text: "Good morning thalaivaa!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "morning greeting boss!", variables: [] },
  { text: "Akka! Eppadi irukkeenga?", emotion: "greeting", intensity: "low", gender: "female", archetype: "any", context: "greeting elder sister", variables: [] },
  { text: "Amma! Vaa! Romba naalaa!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "mom! come! so long!", variables: [] },
  { text: "Yaaru da nee? Theriyalaiye!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "who are you? can't recognize!", variables: [] },
  { text: "Namaskaaram sir!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "greeting teacher", variables: [] },
  { text: "Hey! Inga vaa da!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "come here!", variables: [] },
  { text: "Vaazhga! Vaazhga!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "narrator", context: "long live! (formal welcome)", variables: [] },
  { text: "En kannu! Vaa da!", emotion: "greeting", intensity: "high", gender: "any", archetype: "elder", context: "my dear! come!", variables: [] },
  { text: "Thambi! Enga irundha varrenga?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "brother! where are you from?", variables: [] },
  { text: "Oye! Scene enna da?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "what's the scene?", variables: [] },
  { text: "Ayyaa! Vaanga! Vaanga!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "sir! come! come!", variables: [] },
  { text: "Dei! Unn phone eh edukka maattiya?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "won't you pick up your phone?", variables: [] },
  { text: "VIP vandhuduchu! Welcome!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "VIP arrived! (sarcastic)", variables: [] },
  { text: "Machan! Ready aa?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! ready?", variables: [] },
  { text: "Pa! Eppadi irukka?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "casual friendly greeting", variables: [] },
  { text: "Mapla! Pudhu figure ah?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! new look?", variables: [] },
  { text: "Thangachi! Vaa!", emotion: "greeting", intensity: "medium", gender: "female", archetype: "any", context: "little sister! come!", variables: [] },
  { text: "Anna! Vanakkam!", emotion: "greeting", intensity: "low", gender: "male", archetype: "child", context: "brother! greetings!", variables: [] },
  { text: "Appa! Vandhuduchu!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "child", context: "dad! came!", variables: [] },
  { text: "Chellam! Vaa inga!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "darling! come here!", variables: [] },
  { text: "Maama! Enna vishesham?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "uncle! what's special?", variables: [] },
  { text: "Dei! Alive aa?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "are you alive?", variables: [] },
  { text: "Boss! Scene pottu solla!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "boss! tell me the scene!", variables: [] },
  { text: "Mass entry da!", emotion: "greeting", intensity: "high", gender: "male", archetype: "hero", context: "mass entry!", variables: [] },
  { text: "Varuvaaraanu kaathundukkiten!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "I was waiting for your arrival!", variables: [] },
  { text: "Hello hello! Ovvoru person um ready ah?", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "is everyone ready?", variables: [] },
  { text: "Semma da! Nee vandhuducha!", emotion: "greeting", intensity: "high", gender: "male", archetype: "friend", context: "awesome! you came!", variables: [] },
  { text: "Naan vandhutten da! Start pannu!", emotion: "greeting", intensity: "high", gender: "male", archetype: "any", context: "I've come! start it!", variables: [] },
  { text: "Innaiku enna special?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "what's special today?", variables: [] },
  { text: "Dei {name}! Enna panra?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "what are you doing?", variables: ["{name}"] },
  { text: "Oho! Late aa vandhurukkeenga!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "oh you've come late!", variables: [] },
  { text: "Periyavaa! Asirvatham pannunga!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "elder! bless me!", variables: [] },
  { text: "Master! Good morning!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "teacher greeting", variables: [] },
  { text: "Enga team ah? Assemble!", emotion: "greeting", intensity: "high", gender: "any", archetype: "hero", context: "where's my team? assemble!", variables: [] },
  { text: "Da! Solla solra! Enna aachi?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "tell me! what happened?", variables: [] },
  { text: "Vaanga vaanga! Tea kudippomlaa?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "come! shall we have tea?", variables: [] },
  { text: "Machan! Supera irukkaa?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "bro! doing super?", variables: [] },
  { text: "Yov! Wait pannu!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "hey! wait!", variables: [] },
  { text: "Kalyanam pannikitaano?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "married yet? (teasing greeting)", variables: [] },
  { text: "Nee illa na naan illa!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "without you it's not the same!", variables: [] },
  { text: "Hey! Nee thaan da hero!", emotion: "greeting", intensity: "high", gender: "male", archetype: "friend", context: "you're the hero!", variables: [] },
  { text: "Vaanga! Katcheri start aagudhu!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "narrator", context: "come! the session begins!", variables: [] },
  { text: "En raja! Vaa!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "elder", context: "my king! come!", variables: [] },
  { text: "Enna da ithu! Nee inga?", emotion: "greeting", intensity: "high", gender: "male", archetype: "any", context: "what! you here?", variables: [] },
  { text: "Dei! Group photo eduppomlaa!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "let's take a group photo!", variables: [] },
  { text: "Thalapathi! Vanakkam!", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "leader! greetings!", variables: [] },
  { text: "Pesaamal vaa! Ukkaaru!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "come without talking! sit!", variables: [] },
  { text: "Bro! What's up da?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "Tanglish greeting", variables: [] },
  { text: "Enga area ku welcome!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "welcome to our area!", variables: [] },

  // ============================================================
  // SURPRISE / SHOCK (50)
  // ============================================================
  { text: "Aiyo! Enna nadakkudhu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what's happening!", variables: [] },
  { text: "Kadavule! Ithu enna!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "God! what is this!", variables: [] },
  { text: "Dei! Unmaiyaa?!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "is it true?!", variables: [] },
  { text: "Ayyayyo! Ithu enga solrathu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh no! where to even begin!", variables: [] },
  { text: "Semma da! Ithu nambavay mudiyala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "super! can't believe this!", variables: [] },
  { text: "Ennadaa ithu?!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "what is this?!", variables: [] },
  { text: "Shock aayitten! Full shock!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "I'm shocked! full shock!", variables: [] },
  { text: "Saami! Ithu eppadi possible!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "God! how is this possible!", variables: [] },
  { text: "Poda! Pulicha da!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "go! sour (disgusting)!", variables: [] },
  { text: "Yen da ipdi panniye!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "why did you do this!", variables: [] },
  { text: "Dei! Ithu twist da! Pedha twist!", emotion: "surprise", intensity: "high", gender: "any", archetype: "narrator", context: "this is a twist! big twist!", variables: [] },
  { text: "En kanni naan nambala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "I can't believe my eyes!", variables: [] },
  { text: "Idhukku mela enna nadakkum!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what more can happen!", variables: [] },
  { text: "Plan motham floppu aayiduchu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "entire plan flopped!", variables: [] },
  { text: "Yaaru pannaan ithu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "who did this?!", variables: [] },
  { text: "Eppo nadanduchu ithu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "when did this happen?!", variables: [] },
  { text: "Yemaa! Ithu vera level!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is another level!", variables: [] },
  { text: "Aiyo paavum da!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "oh poor thing!", variables: [] },
  { text: "Ippo solla pora?! Ippo?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "you're telling me now?! now?!", variables: [] },
  { text: "Enna da aachi! Sollu sollu!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "what happened! tell me!", variables: [] },
  { text: "Ithu kanavu illai kadhaa?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "this isn't a dream right?!", variables: [] },
  { text: "Mundhaanaal thaan seri aa irundhuchu!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "it was fine just the other day!", variables: [] },
  { text: "Mass da! Full mass!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "mass! full mass!", variables: [] },
  { text: "Dei! {name} ithu pannaan?! Nambavay mudiyala!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "{name} did this?! unbelievable!", variables: ["{name}"] },
  { text: "Jackpot da! Full jackpot!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "jackpot!", variables: [] },
  { text: "Secret veliya vandhuduchu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "secret is out!", variables: [] },
  { text: "Amma! Paaru ithu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "mom! look at this!", variables: [] },
  { text: "Andha {object} inga eppadi vandhuchu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "how did that get here?!", variables: ["{object}"] },
  { text: "Motha scene eh maariduchu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "the whole scene changed!", variables: [] },
  { text: "Thalai sutrudhu da!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "my head is spinning!", variables: [] },
  { text: "Ivvalo periya irukku!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "it's so big!", variables: [] },
  { text: "Ippo enna panrathu?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what to do now?!", variables: [] },
  { text: "Poiduchu! Ellam poiduchu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "gone! everything's gone!", variables: [] },
  { text: "History da ithu! History!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is history!", variables: [] },
  { text: "Adhisayam da! Pura adhisayam!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "miracle! complete miracle!", variables: [] },
  { text: "Light poiduchu! Iruttaayiduchu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "lights went out! became dark!", variables: [] },
  { text: "Ithu impossible da!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is impossible!", variables: [] },
  { text: "Oru nimisham! Wait pannu!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "one moment! wait!", variables: [] },
  { text: "Naan correct ah thaan ketten da?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "did I hear that right?!", variables: [] },
  { text: "Abba! Pedha vishayam ithu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is a big matter!", variables: [] },
  { text: "Apparam sollu! Apparam!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "then tell me! then!", variables: [] },
  { text: "Oruthan kooda sollala da!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "nobody even told me!", variables: [] },
  { text: "Setthu poiduvom polaye!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "we're going to die it seems!", variables: [] },
  { text: "Money da! Romba money!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "money! lots of money!", variables: [] },
  { text: "Record break aayiduchu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "record has been broken!", variables: [] },
  { text: "Enna timing da! Exact ah vandhutte!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what timing! came exactly right!", variables: [] },
  { text: "Asingama pochu da!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "got embarrassed!", variables: [] },
  { text: "Mokka da! Full mokka!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "rubbish! total rubbish!", variables: [] },
  { text: "Vera level content da!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "another level content!", variables: [] },
  { text: "Konjam neram pochu! Already time over!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "time passed! already over!", variables: [] },

  // ============================================================
  // ANGER (45)
  // ============================================================
  { text: "Poda! Pakkam poo!", emotion: "anger", intensity: "high", gender: "male", archetype: "any", context: "go away!", variables: [] },
  { text: "Vaaya moodu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "shut your mouth!", variables: [] },
  { text: "Dei! Romba aagudhu!", emotion: "anger", intensity: "high", gender: "male", archetype: "any", context: "it's getting too much!", variables: [] },
  { text: "En thalai la yeri okkaara!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't sit on my head (annoy me)!", variables: [] },
  { text: "Nee mela nambikkai poiduchu!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "lost trust in you!", variables: [] },
  { text: "Nee veyala ithu ellam aachi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "all this happened because of you!", variables: [] },
  { text: "Summa irunthaa sukhama irukkum!", emotion: "anger", intensity: "medium", gender: "any", archetype: "elder", context: "if you stay quiet you'll be happy!", variables: [] },
  { text: "Innum oru vaarthai sonnaa...", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "if you say one more word...", variables: [] },
  { text: "Thirutham theriyaadha unaaku!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "you'll never change!", variables: [] },
  { text: "Jaakkirathai! Munnadi varaadha!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "beware! don't come forward!", variables: [] },
  { text: "Ippo limit cross pannitey!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "you just crossed the limit!", variables: [] },
  { text: "Enna vida mosam aana aalu illa!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "nobody worse than me (victim)", variables: [] },
  { text: "Nee mugam paakka agala!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I can't look at your face!", variables: [] },
  { text: "Naan sonna kekkamattiya?!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "won't you listen to what I say?!", variables: [] },
  { text: "Yov! Mokka podaadha!", emotion: "anger", intensity: "high", gender: "male", archetype: "any", context: "don't crack bad jokes!", variables: [] },
  { text: "Ithu thappu! Periya thappu!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "this is wrong! big mistake!", variables: [] },
  { text: "Enna pudichaa? Kuthiraiyaa?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "what do you take me for?!", variables: [] },
  { text: "Poiduvom aiyyaa! Poiduvom!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "let's go! let's just go!", variables: [] },
  { text: "Nee kooda pesa virumbala!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "I don't want to talk to you!", variables: [] },
  { text: "Dhrogam! Periya dhrogam!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "betrayal! big betrayal!", variables: [] },
  { text: "En mela kathara!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "you're yelling at ME?!", variables: [] },
  { text: "Veetla solluvein! Oduvein!", emotion: "anger", intensity: "medium", gender: "any", archetype: "child", context: "I'll tell at home! you'll get it!", variables: [] },
  { text: "Ippo sollu! Enna panniye!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "tell me now! what did you do!", variables: [] },
  { text: "Paathukko! Regret pannuva!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "watch out! you'll regret!", variables: [] },
  { text: "Enna perusa nenaichukittu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "who do you think you are!", variables: [] },
  { text: "Veliya poo! Ippo!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "get out! now!", variables: [] },
  { text: "Naan yaar nu theriyumaa?!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "do you know who I am?!", variables: [] },
  { text: "Romba patience kaathinein!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I showed too much patience!", variables: [] },
  { text: "Again same mistake ah?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "same mistake again?!", variables: [] },
  { text: "Enna thani aa vittudu!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "leave me alone!", variables: [] },
  { text: "Nee tricks ellam inga velaikkaadhu!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "your tricks won't work here!", variables: [] },
  { text: "Nee mela oru kovam varudhu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "anger is building up against you!", variables: [] },
  { text: "Naatakam pannaadhey!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't act!", variables: [] },
  { text: "Vekkam illai unakku?!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "aren't you ashamed?!", variables: [] },
  { text: "Naan mannikkamaatten!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I won't forgive!", variables: [] },
  { text: "Poi unna paathukko!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "go look after yourself!", variables: [] },
  { text: "Enakku vendaam! Poo!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I don't need! go!", variables: [] },
  { text: "Nee mudivai paappom!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "I'll see your fate!", variables: [] },
  { text: "Unaala thaan ellam keduchu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "everything is ruined because of you!", variables: [] },
  { text: "Ippo oru nool la thongudhu en patience!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "my patience hangs by a thread!", variables: [] },
  { text: "Control panniko!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "control yourself!", variables: [] },
  { text: "Pesaamal iru! Pesaamal!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "stay quiet! quiet!", variables: [] },
  { text: "Enakku theriyadha unna?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I don't know you?!", variables: [] },
  { text: "Unna yaaravadhu kaappathuvaa?!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "will anyone save you?!", variables: [] },
  { text: "Maraiya poo! En munnadi varaadha!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "disappear! don't come before me!", variables: [] },

  // ============================================================
  // FEAR (40)
  // ============================================================
  { text: "Amma! Bayama irukku!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "mom! it's scary!", variables: [] },
  { text: "Pei! Odunga!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "ghost! run!", variables: [] },
  { text: "Saamiyo! Kaappaathungo!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "God! save us!", variables: [] },
  { text: "Enakku romba bayama irukku!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "I'm very scared!", variables: [] },
  { text: "Anga paakaadhey! Anga enna irukku!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look there!", variables: [] },
  { text: "Odunga! Seekiram!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "run! fast!", variables: [] },
  { text: "Yaaru da anga?!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "who's there?!", variables: [] },
  { text: "Kaal nadungudhu da bayathula!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "legs shaking with fear!", variables: [] },
  { text: "Ingirundhu poidiuvom! Vaa!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "let's get out! come!", variables: [] },
  { text: "Thirumbi paakaadhey! Odu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look back! run!", variables: [] },
  { text: "Paambu! Paambu irukkudi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "snake! there's a snake!", variables: [] },
  { text: "Veetukku poidiuvom! Ippo!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "let's go home! now!", variables: [] },
  { text: "Adhu varudhu! Adhu varudhu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's coming! it's coming!", variables: [] },
  { text: "Olinjikko! Seekiram!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "hide! quickly!", variables: [] },
  { text: "Thani aa irukkamudiyaadhu inga!", emotion: "fear", intensity: "medium", gender: "any", archetype: "child", context: "can't be alone here!", variables: [] },
  { text: "Kai pudicho da!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "hold my hand!", variables: [] },
  { text: "Light poiduchu! Iruttaayiduchu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "lights went out! dark!", variables: [] },
  { text: "Enna saththam adhu?!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "what was that sound?!", variables: [] },
  { text: "En nenjadithu romba vegama irukku!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "my heart is beating fast!", variables: [] },
  { text: "Help! Yaaravadhu vaanga!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "help! someone come!", variables: [] },
  { text: "Ithu shaapam irukkira idam!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "this place is cursed!", variables: [] },
  { text: "Enakku enna thaan therinjadhu! Nijama!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "I saw something! for real!", variables: [] },
  { text: "Shhh! Saththam podaadha! Kekkum!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "shh! don't make noise! it'll hear!", variables: [] },
  { text: "Ithu bommaan da! Fasaayittom!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's a trap! we're caught!", variables: [] },
  { text: "Veliya vazhiye illai!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "no way out!", variables: [] },
  { text: "Nee ellaam ponga! Naan thaduppein!", emotion: "fear", intensity: "high", gender: "male", archetype: "hero", context: "you all go! I'll stop it!", variables: [] },
  { text: "Bayapadaadha! Naan irukken!", emotion: "fear", intensity: "medium", gender: "any", archetype: "hero", context: "don't be afraid! I'm here!", variables: [] },
  { text: "Inga enna rightaa illa da!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "something isn't right here!", variables: [] },
  { text: "Adhu en pakkam paakkudhu! Paaru!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's looking at me! look!", variables: [] },
  { text: "Kaatukku ulle povaadha!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't go into the forest!", variables: [] },
  { text: "Kathavu moodu! Seekiram!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "close the door! quickly!", variables: [] },
  { text: "Inniku raathri enna aagumoo!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "what will happen tonight!", variables: [] },
  { text: "Edhuvoo aasadhikkudhu da!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "something is moving!", variables: [] },
  { text: "Verri kanavu vandhuchu! Bayangara kanavu!", emotion: "fear", intensity: "medium", gender: "any", archetype: "child", context: "I had a nightmare!", variables: [] },
  { text: "Adhu monster da! Periya monster!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "it's a monster! big one!", variables: [] },
  { text: "En uyir pochu bayathula!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "my life left from fear!", variables: [] },
  { text: "Kaal nagaraadhu da bayathula!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "can't move feet from fear!", variables: [] },
  { text: "Light kondu vaa! Onnum theriyala!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "bring light! can't see anything!", variables: [] },
  { text: "En pinnaadi yaaro nikkuraan!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "someone's standing behind me!", variables: [] },
  { text: "Inga edhuvum sari aa illa!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "nothing is right here!", variables: [] },

  // ============================================================
  // HAPPINESS (45)
  // ============================================================
  { text: "Semma da! Mast irukku!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "awesome!", variables: [] },
  { text: "Jeyichittom! Namma team jeyichiduthu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "we won!", variables: [] },
  { text: "Thara da! Full thara!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "rocking! fully rocking!", variables: [] },
  { text: "Aahaa! Idhu thaan nijamana sandhosham!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "this is real happiness!", variables: [] },
  { text: "Party time da! Celebration!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "party time!", variables: [] },
  { text: "Pannittom da! Pannittom!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "we did it!", variables: [] },
  { text: "Super ah pannittey da!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "you did it super!", variables: [] },
  { text: "Kanavu nijam aachudi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "dream came true!", variables: [] },
  { text: "Laddu distribute pannunga!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "distribute laddus!", variables: [] },
  { text: "Nee genius da!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're a genius!", variables: [] },
  { text: "Best day ever da!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "best day ever!", variables: [] },
  { text: "En kashtam palichudu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "hero", context: "my hard work paid off!", variables: [] },
  { text: "Kadavulukku nandri!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "thanks to God!", variables: [] },
  { text: "Dance aaduvom da! Inniku special!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "let's dance! today is special!", variables: [] },
  { text: "Full marks da! Full marks vandhuchu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "got full marks!", variables: [] },
  { text: "{name}! Nee romba great da!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're very great!", variables: ["{name}"] },
  { text: "Idhu winning moment da!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "winning moment!", variables: [] },
  { text: "Ellaarukum thanks sollanum!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "must thank everyone!", variables: [] },
  { text: "Ivvalavu nalla naal!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "such a great day!", variables: [] },
  { text: "Namma team number one!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "our team number one!", variables: [] },
  { text: "Sandhoshathula kanneer varudhu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "tears of happiness!", variables: [] },
  { text: "Paaru paaru! Nanga pannittom!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "look! we did it!", variables: [] },
  { text: "Ice cream saappduvom! Celebrate!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "let's eat ice cream!", variables: [] },
  { text: "Veetla poi solluven!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "going home to tell!", variables: [] },
  { text: "Amma! Naan pass aaiten!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "mom! I passed!", variables: [] },
  { text: "Idhu teamwork da! Pure teamwork!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "this is teamwork!", variables: [] },
  { text: "Records break pannittom!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "broke records!", variables: [] },
  { text: "Oru cinema maadiri irukku life!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "life's like a movie!", variables: [] },
  { text: "Champion! Nee champion da!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "you're a champion!", variables: [] },
  { text: "Miracle da ithu! Pure miracle!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "this is a miracle!", variables: [] },
  { text: "Biriyani saappduvom! En treat!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "biryani for all! my treat!", variables: [] },
  { text: "Maaasskku! Standing ovation!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "mass! standing ovation!", variables: [] },
  { text: "Namba heroes ellam! Heroes!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "you're all heroes!", variables: [] },
  { text: "Kashtam aana worth it da!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "tough but worth it!", variables: [] },
  { text: "Golden moment da ithu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "narrator", context: "golden moment!", variables: [] },
  { text: "Hip hip hurray!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "hip hip hooray!", variables: [] },
  { text: "Vera level scene da!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "another level scene!", variables: [] },
  { text: "Aala vidaa scene da!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "incomparable scene!", variables: [] },
  { text: "Inimel life maarum da!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "life will change from now!", variables: [] },
  { text: "Adra sakki! Pannittom!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "oh yeah! we did it!", variables: [] },
  { text: "Ennoda prarthana ketuduchu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "my prayer was heard!", variables: [] },
  { text: "Innum solluvein? Best news ithu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "shall I say more? this is the best news!", variables: [] },
  { text: "Mass da! Full mass nu sollu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "say it! full mass!", variables: [] },
  { text: "Orey! Orey! Orey!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "victory chant!", variables: [] },
  { text: "Ulagathula best team da namma!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "we're the best team in the world!", variables: [] },

  // ============================================================
  // THINKING + NARRATION + MORAL + CATCHPHRASE + FILLER (~200)
  // ============================================================
  // THINKING (40)
  { text: "Hmm... yosikaanum!", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "must think!", variables: [] },
  { text: "Enakku oru idea varudhu!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "I'm getting an idea!", variables: [] },
  { text: "Aagu aagu... puriyudhu!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "wait, I understand!", variables: [] },
  { text: "Adhoda meaning enna na...", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "its meaning is...", variables: [] },
  { text: "Namma ipdi pannaa?", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "what if we do this?", variables: [] },
  { text: "Enakku oru plan irukku!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "hero", context: "I have a plan!", variables: [] },
  { text: "Yosinga... {object} illainaa?", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "think... without this?", variables: ["{object}"] },
  { text: "Purinjudhaa? Naan solla varadhu?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "understood? what I'm saying?", variables: [] },
  { text: "Brain use pannu da! Brain!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "use your brain!", variables: [] },
  { text: "Aaha! Ippo purinjiduchu!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "now I understand!", variables: [] },
  { text: "Vera angle la yosippom!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "think from another angle!", variables: [] },
  { text: "Thappu la irundhu kaththukko!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "learn from mistakes!", variables: [] },
  { text: "Unakku enna thonudhu?", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "what do you think?", variables: [] },
  { text: "Naan yosikirein...", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "I'm thinking...", variables: [] },
  { text: "Answer romba simple da!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "answer is very simple!", variables: [] },
  { text: "Problem irundha solution um irukkum!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "if there's a problem there's a solution!", variables: [] },
  { text: "Wait wait wait! Eureka da!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "eureka!", variables: [] },
  { text: "Practice la ellam saadiyam!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "everything possible with practice!", variables: [] },
  { text: "Hmmm... interesting... romba interesting!", emotion: "thinking", intensity: "low", gender: "any", archetype: "villain", context: "villain finding it interesting", variables: [] },
  { text: "Enga thappu nadandhuchu? Paappom!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "where did the mistake happen?", variables: [] },
  { text: "Idhu clue da! Definite clue!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "this is a clue!", variables: [] },
  { text: "Ippo bulb on aachudi!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "the bulb just turned on!", variables: [] },
  { text: "Ellaarukum sollungal! Vazhi kidachudi!", emotion: "thinking", intensity: "high", gender: "any", archetype: "hero", context: "tell everyone! found the way!", variables: [] },
  { text: "Idhu pattern da! Paakkuriyaa?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "this is a pattern! see it?", variables: [] },
  { text: "Ippo purinjudhaa?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "now you understand?", variables: [] },
  { text: "Oivaa porumya vaikkanum!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "must have patience!", variables: [] },
  { text: "Badhil un kitta thaan irukku!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "the answer is with you!", variables: [] },
  { text: "Kal thooki kalai podu maadiri!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "like throwing a stone at your own foot (proverb)", variables: [] },
  { text: "Konjam think pannu before action!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "think before action!", variables: [] },
  { text: "Step by step ah pannuvom!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "let's do step by step!", variables: [] },
  // NARRATION (30)
  { text: "Aprom enna nadandhuchu? Kelunga!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "what happened next? listen!", variables: [] },
  { text: "Romba kaalam munnaadi...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "long long ago...", variables: [] },
  { text: "Ippo aduttha kathai kelunga!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "now listen to the next story!", variables: [] },
  { text: "Oru ooru la oru {object} irundhadhu...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "in a village there was a...", variables: ["{object}"] },
  { text: "Aanaa kathai inga mudiyala!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "but the story doesn't end here!", variables: [] },
  { text: "Paappom enna nadakkudhu nu!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "let's see what happens!", variables: [] },
  { text: "Ippo nijamana kathai start!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "now the real story starts!", variables: [] },
  { text: "Sila manikku apram...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "after a few hours...", variables: [] },
  { text: "Marunaal kaalaila...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "next day morning...", variables: [] },
  { text: "Ipdi oru pudhu adventure start aachudi!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "a new adventure started!", variables: [] },
  { text: "Ellaarum ninachaa mudinjiduchu nu... aanaa!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everyone thought it was over... but!", variables: [] },
  { text: "Andha naal vandhuchu...", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "that day came...", variables: [] },
  { text: "{name} panniduvaaraa? Paappom!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "will they do it? let's see!", variables: ["{name}"] },
  { text: "Appo yarum ethir paarkadha vishayam nadandhuchu!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "then something unexpected happened!", variables: [] },
  { text: "Appo... suddenly...", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "then... suddenly...", variables: [] },
  { text: "Ellam maara pogudu!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everything is about to change!", variables: [] },
  { text: "Mudhal part la paathom...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "in the first part we saw...", variables: [] },
  { text: "Ippo paappom {name} enna panraar nu!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "now let's see what they do!", variables: ["{name}"] },
  { text: "Kathaila innum oru twist!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "another twist in the story!", variables: [] },
  { text: "Ee kathaiyoda hero yaaru na...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "the hero of this story is...", variables: [] },
  { text: "Final round! Kadaisi chance!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "final round! last chance!", variables: [] },
  { text: "Ithu trailer thaan! Padam innum irukku!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "this is just the trailer!", variables: [] },
  { text: "Neriyu climax ku povom!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "let's go to the climax!", variables: [] },
  { text: "Ee kathai nyaabakam vaikkanum!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "remember this story!", variables: [] },
  { text: "Ippo kathai munnadi pogudu...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "now the story moves forward...", variables: [] },
  { text: "Idhu varai kEttagala? Adutthu varudhu!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "heard so far? next is coming!", variables: [] },
  { text: "Oru pakkam... marubakkam...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "on one side... on the other...", variables: [] },
  { text: "Kaalam maariduchu...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "times changed...", variables: [] },
  { text: "Aanaa nijamavay ellam sari aachaa?", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "but did everything really become okay?", variables: [] },
  { text: "Idhu oru pudhu thodakkam!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "this is a new beginning!", variables: [] },
  // MORAL (30)
  { text: "Adhanaala solluvaanga... kashtapaddinaa palanum kidaikkum!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "hard work brings results!", variables: [] },
  { text: "Paadham ennana... poi sollakooadaadhu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "lesson: don't lie!", variables: [] },
  { text: "Kuzhanthaigale! Innaiku enna kaththukkittom?", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "kids! what did we learn today?", variables: [] },
  { text: "Unmai yeppovum vellum!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "truth always wins!", variables: [] },
  { text: "Nanbarkal thaan periya balam!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "friends are the greatest strength!", variables: [] },
  { text: "Thairiyam vittudalaadhey yeppavum!", emotion: "moral", intensity: "high", gender: "any", archetype: "mentor", context: "never give up courage!", variables: [] },
  { text: "Periyavanga solradhu kekkaNum!", emotion: "moral", intensity: "low", gender: "any", archetype: "elder", context: "listen to what elders say!", variables: [] },
  { text: "Avasaram thappu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "haste is wrong!", variables: [] },
  { text: "Orumai thaan balam!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "unity is strength!", variables: [] },
  { text: "Peraasai azhivu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "greed is destruction!", variables: [] },
  { text: "Kashtakaalathula unmaiyaana nanban theriyum!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "true friends show in tough times!", variables: [] },
  { text: "Mathavargalukku udhavinaa... unaakkum udavi varum!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "help others and help comes!", variables: [] },
  { text: "Bayam kadandha jeyam irukku!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "victory beyond fear!", variables: [] },
  { text: "Sinna sinna vishayam periya maatram thaarum!", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "small things bring big changes!", variables: [] },
  { text: "Thappu opukka thairiyam veNum!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "admitting mistakes needs courage!", variables: [] },
  { text: "Kalvikku vayasu illai!", emotion: "moral", intensity: "low", gender: "any", archetype: "mentor", context: "no age for education!", variables: [] },
  { text: "Kootti pannaa ellam saadiyam!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "together everything is possible!", variables: [] },
  { text: "Ee paadham nyaabakam vaikkanum!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "remember this lesson!", variables: [] },
  { text: "Kattrukkondey irungal!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "never stop learning!", variables: [] },
  { text: "Enna nadandhalum unmai sollu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "speak truth no matter what!", variables: [] },
  { text: "Life la shortcuts vElaikkaadhu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "shortcuts don't work in life!", variables: [] },
  { text: "Yaarayum chinnathaa nenaikkaadhey!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "don't underestimate anyone!", variables: [] },
  { text: "Vittukottavan yeppavum jeyikka maattan!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "quitters never win!", variables: [] },
  { text: "Amma appa sevai periya dharmam!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "serving parents is great duty!", variables: [] },
  { text: "Naermai nalla neethi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "honesty is the best policy!", variables: [] },
  { text: "Kanavu veikkadhey! Nadanthu kaattiru!", emotion: "moral", intensity: "high", gender: "any", archetype: "mentor", context: "don't just dream! walk the walk!", variables: [] },
  { text: "Poruma kunam semmaya palikkum!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "patience pays off well!", variables: [] },
  { text: "Nanbargale! Enna kaththukkitteenga?", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "friends! what did you learn?", variables: [] },
  { text: "Nalladu pannaa nalladu varum!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "do good get good!", variables: [] },
  { text: "Aduttha episode la innum kaththukkuvom! Bye!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "learn more next episode!", variables: [] },
  // CATCHPHRASES (25)
  { text: "En per {name}! Naan yeppovum ready!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "hero intro", variables: ["{name}"] },
  { text: "Idhu en specialty da!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "this is my specialty", variables: [] },
  { text: "Hm hm hm... plan work aagudhu!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "villain", context: "plan is working", variables: [] },
  { text: "Ungalaalaa ennai thadukka mudiyaadhu!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "you can't stop me!", variables: [] },
  { text: "Paravailla! Maarum try pannom!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "no problem! let's try again!", variables: [] },
  { text: "Mudhal saappaadu! Matha ellam appram!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "food first! rest later!", variables: [] },
  { text: "Mission start da!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "mission start!", variables: [] },
  { text: "Power up!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "power up!", variables: [] },
  { text: "Game over villains!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "game over!", variables: [] },
  { text: "Naan thirinji varuven!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "I will return!", variables: [] },
  { text: "Full power la! Let's go!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "full power!", variables: [] },
  { text: "Naan thokkamaatten!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "I won't lose!", variables: [] },
  { text: "Saappaadu enga da?!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "where's the food?!", variables: [] },
  { text: "Tension edukkaadha da!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "don't take tension!", variables: [] },
  { text: "Thala da thala!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "boss! the boss!", variables: [] },
  { text: "Mass entry panniduvom!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "making a mass entry!", variables: [] },
  { text: "Idhu en final move!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "this is my final move!", variables: [] },
  { text: "Naan yaaru theriyumaa?!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "do you know who I am?!", variables: [] },
  { text: "Enakku thookkam varudhu...", emotion: "catchphrase", intensity: "low", gender: "any", archetype: "comic", context: "I'm getting sleepy...", variables: [] },
  { text: "Level complete!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "level complete!", variables: [] },
  { text: "Shhh! Top secret!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "any", context: "top secret!", variables: [] },
  { text: "Gethu da gethu!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "style! total style!", variables: [] },
  { text: "Vera maadiri!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "unique! different!", variables: [] },
  { text: "Naan joke pannein da!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "I was joking!", variables: [] },
  { text: "En team a nambungal!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "trust my team!", variables: [] },
  // FILLERS (25)
  { text: "Sari sari!", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "okay okay", variables: [] },
  { text: "Sollu da!", emotion: "filler", intensity: "medium", gender: "male", archetype: "any", context: "tell me!", variables: [] },
  { text: "Aagu aagu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "wait wait!", variables: [] },
  { text: "Adhu illa...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "that's not it...", variables: [] },
  { text: "Hmm... correct!", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "hmm correct!", variables: [] },
  { text: "Paaru paaru!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "look look!", variables: [] },
  { text: "Kelu kelu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "listen listen!", variables: [] },
  { text: "Apdi thaan...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "like that...", variables: [] },
  { text: "Aama aama!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "yes yes!", variables: [] },
  { text: "Illa illa!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "no no!", variables: [] },
  { text: "Vaa da!", emotion: "filler", intensity: "medium", gender: "male", archetype: "any", context: "come!", variables: [] },
  { text: "Poda!", emotion: "filler", intensity: "medium", gender: "male", archetype: "any", context: "go!", variables: [] },
  { text: "Oru nimisham!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "one moment!", variables: [] },
  { text: "Theriyum theriyum!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "I know I know!", variables: [] },
  { text: "Next!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "next!", variables: [] },
  { text: "Simple da!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "simple!", variables: [] },
  { text: "Done da!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "done!", variables: [] },
  { text: "Ready aa?", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "ready?", variables: [] },
  { text: "Basically...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "basically", variables: [] },
  { text: "Actually...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "actually", variables: [] },
  { text: "Enna solreer?", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "what are you saying?", variables: [] },
  { text: "Wait pannu da!", emotion: "filler", intensity: "medium", gender: "male", archetype: "any", context: "wait!", variables: [] },
  { text: "Vidungo!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "leave it!", variables: [] },
  { text: "Point!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "good point!", variables: [] },
  { text: "Tension edukkaadha!", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "don't worry!", variables: [] },
  // ENCOURAGEMENT (15)
  { text: "Unnaal mudiyum da!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "you can do it!", variables: [] },
  { text: "Thairiyam vita kooodaadhu!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "don't lose courage!", variables: [] },
  { text: "Maarum try pannu!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "try again!", variables: [] },
  { text: "Naan un pakkam irukken!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "friend", context: "I'm on your side!", variables: [] },
  { text: "Nalla pannittey! Innum nalla pannu!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "did well! do even better!", variables: [] },
  { text: "Jeyam paakkathula irukku!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "victory is nearby!", variables: [] },
  { text: "Sabash da!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "elder", context: "well done!", variables: [] },
  { text: "Nee romba brave da!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "you're very brave!", variables: [] },
  { text: "Naanga ellam un pakkam!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "friend", context: "we're all with you!", variables: [] },
  { text: "Konjam more! Bas konjam!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "a little more!", variables: [] },
  { text: "Un mela nambikkai irukku!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "I trust you!", variables: [] },
  { text: "Ezhundhu nillu! Maarum poru!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "get up! fight again!", variables: [] },
  { text: "Come on! Come on! Come on!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "any", context: "cheering on!", variables: [] },
  { text: "Go go go da!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "any", context: "go go go!", variables: [] },
  { text: "Nee vera level da!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "you're another level!", variables: [] },
  // WARNING (10)
  { text: "Jaakkirathai! Abaayam!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "careful! danger!", variables: [] },
  { text: "Anga pookaadhey! Dangerous!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "don't go there!", variables: [] },
  { text: "Paathukko! Keezha paaru!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "careful! look down!", variables: [] },
  { text: "Thottadha! Visham irukku!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "don't touch! poison!", variables: [] },
  { text: "Pinna poo! Pinna!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "get back!", variables: [] },
  { text: "Jaakkirathai! Pomman irukku!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "beware! it's a trap!", variables: [] },
  { text: "Pannaadhey! Romba kedukkum!", emotion: "warning", intensity: "high", gender: "any", archetype: "elder", context: "don't! it will go bad!", variables: [] },
  { text: "Neram illa! Seekiram pannu!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "no time! do it fast!", variables: [] },
  { text: "Ithu {name} plan da! Fasaadha!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "it's their plan! don't fall for it!", variables: ["{name}"] },
  { text: "Last warning da ithu!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "this is the last warning!", variables: [] },
  // DETERMINATION + GRATITUDE + CELEBRATION (15)
  { text: "Ippo nirkkakkooodaadhu!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "can't stop now!", variables: [] },
  { text: "Naan panniye kaattuven!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "I will prove it!", variables: [] },
  { text: "Enna nadandhalum sari!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "no matter what!", variables: [] },
  { text: "Naan haar accept pannamatten!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "I won't accept defeat!", variables: [] },
  { text: "Idhu en promise da!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "this is my promise!", variables: [] },
  { text: "Thanks da! Romba help aachudi!", emotion: "gratitude", intensity: "medium", gender: "any", archetype: "any", context: "thanks! helped a lot!", variables: [] },
  { text: "Nandri! Manasa solren!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "heartfelt thanks!", variables: [] },
  { text: "Nee illaama naan illa!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "without you I'm nothing!", variables: [] },
  { text: "Kadavul unakku nalladu pannattum!", emotion: "gratitude", intensity: "medium", gender: "any", archetype: "elder", context: "may God bless you!", variables: [] },
  { text: "{name}! Nee best friend da!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "friend", context: "you're the best friend!", variables: ["{name}"] },
  { text: "Party time da! Celebration!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "party time!", variables: [] },
  { text: "Jeyichittom! Champions!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "we won! champions!", variables: [] },
  { text: "Hip hip hurray!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "hip hip hooray!", variables: [] },
  { text: "Vaazhthukkal! Vaazhthukkal!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "congratulations!", variables: [] },
  { text: "Number 1 da namba! Number 1!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "we're number 1!", variables: [] },
];

export const tamilBank: DialogueBank = {
  language: 'tamil',
  isoCode: 'ta-IN',
  displayName: 'Tamil',
  lines,
};
