/**
 * Expert 2: Brahmanandam Style — Telugu Comedy Dialogue Bank
 * 500+ natural Telugu dialogues with Hyderabadi + Andhra colloquial slang.
 */

import { DialogueBank, DialogueLine } from './types';

const lines: DialogueLine[] = [
  // ============================================================
  // GREETINGS (55)
  // ============================================================
  { text: "Enti ra! Baagunnara?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "casual greeting", variables: [] },
  { text: "Ra ra ra! Raandi raandi!", emotion: "greeting", intensity: "high", gender: "male", archetype: "any", context: "welcoming warmly", variables: [] },
  { text: "Namaskaram! Ela unnaru?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "respectful greeting", variables: [] },
  { text: "Emi ra! Enni rojulu ayyindi!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "long time no see", variables: [] },
  { text: "Orey! Nuvvu ikkada?!", emotion: "greeting", intensity: "high", gender: "male", archetype: "any", context: "surprised to see someone", variables: [] },
  { text: "Kya re! Kya haal hai?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "Hyderabadi greeting", variables: [] },
  { text: "Raa babu! Kurchoo!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "elder", context: "come sit down (welcoming)", variables: [] },
  { text: "Bhale bhale! Evaru vaccharu chudandi!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "look who's come!", variables: [] },
  { text: "Good morning ra! Emi visheshalu?", emotion: "greeting", intensity: "low", gender: "male", archetype: "any", context: "morning greeting", variables: [] },
  { text: "Arre bhai! Kya scene hai?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "Hyderabadi casual", variables: [] },
  { text: "Namasthe guruvu gaaru!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "greeting teacher respectfully", variables: [] },
  { text: "Oy! Ikkadiki raara!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "calling someone over", variables: [] },
  { text: "Ammayi! Raandi raandi!", emotion: "greeting", intensity: "medium", gender: "female", archetype: "elder", context: "welcoming a girl/woman", variables: [] },
  { text: "Em chesthunnav ra?", emotion: "greeting", intensity: "low", gender: "male", archetype: "friend", context: "what are you doing?", variables: [] },
  { text: "Oho! VIP vachesaaru!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "VIP has arrived (sarcastic)", variables: [] },
  { text: "Enti mama! Ekkada poyav?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "where were you bro?", variables: [] },
  { text: "Baga vunnav kadaa?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "you're doing well right?", variables: [] },
  { text: "Raa pillaa! Raa!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "come child, come!", variables: [] },
  { text: "Akkada evaru? Ikkadiki randi!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "who's there? come here!", variables: [] },
  { text: "Em ra! Zinda hai ke nahi?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "Hyderabadi are you alive?", variables: [] },
  { text: "Ayyagaaru! Pranaamam!", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "greeting elder with respect", variables: [] },
  { text: "Hai hai! Ante meeru vacchesaru!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "oh you've come!", variables: [] },
  { text: "Chal re! Andariki cheppudam!", emotion: "greeting", intensity: "high", gender: "male", archetype: "friend", context: "let's tell everyone!", variables: [] },
  { text: "Em mama! Em jarigindhi?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "what happened bro?", variables: [] },
  { text: "Osthara bhayya? Ekkada unnaav?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "are you coming? where are you?", variables: [] },
  { text: "Arre! {name} bhai! Kidhar the?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "Hyderabadi where were you?", variables: ["{name}"] },
  { text: "Super ra! Nuvvu vacchav ante party!", emotion: "greeting", intensity: "high", gender: "male", archetype: "friend", context: "you came means party!", variables: [] },
  { text: "Akkayya! Baagunnaaraa?", emotion: "greeting", intensity: "low", gender: "female", archetype: "any", context: "greeting elder sister", variables: [] },
  { text: "Swagatam! Swagatam!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "narrator", context: "welcome! welcome!", variables: [] },
  { text: "Orey nee kosam chusthunna!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "I was looking for you!", variables: [] },
  { text: "Amma! Vacchesindi ra!", emotion: "greeting", intensity: "medium", gender: "female", archetype: "child", context: "mom is here!", variables: [] },
  { text: "Kya re! Tension mat le!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "Hyderabadi don't worry greeting", variables: [] },
  { text: "Enti! Intha late?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "why so late?", variables: [] },
  { text: "Chala kaalam tarvatha kalusukunnam!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "meeting after a long time!", variables: [] },
  { text: "Prabhaatam! Andaru lechipoyi untaaru kadhaa?", emotion: "greeting", intensity: "low", gender: "any", archetype: "narrator", context: "morning! everyone's up right?", variables: [] },
  { text: "Vaadiki cheppu ra! Nenu vachesanu ani!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "tell him I've arrived!", variables: [] },
  { text: "Mee intiki vacchanu! Intlo evaru unnaru?", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "came to your house, who's home?", variables: [] },
  { text: "Chal! Shuru karte hai!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "Hyderabadi let's start!", variables: [] },
  { text: "Oi oi oi! Chala happy ga unnav!", emotion: "greeting", intensity: "high", gender: "any", archetype: "any", context: "you seem very happy!", variables: [] },
  { text: "Nenu vachesa! Party start cheyandi!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "I'm here! start the party!", variables: [] },
  { text: "Babu! Naaku oka help kavali!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "greeting with request for help", variables: [] },
  { text: "Mastaaru! Ela unnaru?", emotion: "greeting", intensity: "low", gender: "any", archetype: "child", context: "how are you teacher?", variables: [] },
  { text: "Anna! Raa! Nee kosam waiting!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "any", context: "brother! come! waiting for you!", variables: [] },
  { text: "Oy re! Pachha kuda tirigav?", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "did you turn around too?", variables: [] },
  { text: "Vandanam andhariki!", emotion: "greeting", intensity: "low", gender: "any", archetype: "narrator", context: "greetings to all!", variables: [] },
  { text: "Helo helo! Testing testing!", emotion: "greeting", intensity: "high", gender: "any", archetype: "comic", context: "funny dramatic greeting", variables: [] },
  { text: "Oho! Meeru kuda vaccharu?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "oh you came too?", variables: [] },
  { text: "Naanna! Ikkada choodu!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "child", context: "dad! look here!", variables: [] },
  { text: "Ante... nuvvu vacchav ante... santhosham!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "you coming makes me happy!", variables: [] },
  { text: "Pedha manishi vachesaaru! Dandam!", emotion: "greeting", intensity: "low", gender: "any", archetype: "any", context: "big person has come! salute!", variables: [] },
  { text: "Raa mawa! Jarigindhi vinali!", emotion: "greeting", intensity: "medium", gender: "male", archetype: "friend", context: "come bro! you need to hear this!", variables: [] },
  { text: "Idhi naa area! Welcome!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "this is my area! welcome!", variables: [] },
  { text: "Oy {name}! Enni rojulayyindhi!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "friend", context: "how many days it's been!", variables: ["{name}"] },
  { text: "Enti! Antha quick ga vachesaav?", emotion: "greeting", intensity: "medium", gender: "any", archetype: "any", context: "you came so quickly?", variables: [] },
  { text: "Bujji! Raa ikkadiki!", emotion: "greeting", intensity: "medium", gender: "any", archetype: "elder", context: "little one! come here!", variables: [] },

  // ============================================================
  // SURPRISE / SHOCK (55)
  // ============================================================
  { text: "Arey baapre!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh my god!", variables: [] },
  { text: "Enti! Nijamena?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what! is it true?!", variables: [] },
  { text: "Devudaa! Idi enti!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "God! what is this!", variables: [] },
  { text: "Nakku tension vasthundi ra!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "Hyderabadi I'm getting tension!", variables: [] },
  { text: "Arey! Idhi expect cheyyaledhu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "didn't expect this!", variables: [] },
  { text: "Emaindhi ra?! Cheppu cheppu!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "what happened?! tell me!", variables: [] },
  { text: "Nammakam kadhu! Idhantha nijama?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "unbelievable! is all this real?!", variables: [] },
  { text: "Avunu! Nenu chusanu! Naa kallatho!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "yes! I saw it! with my own eyes!", variables: [] },
  { text: "Abba! Idi chala pedda vishayam!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is a very big matter!", variables: [] },
  { text: "Yemitidi?! Edhi ekkadnunchi vacchindhi?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what?! where did this come from?!", variables: [] },
  { text: "Oh my God! Idi jarigindha?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "OMG! did this happen?!", variables: [] },
  { text: "Kya re! Ye kya hua?!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "Hyderabadi what happened?!", variables: [] },
  { text: "Poyi poyi ippudu cheppav?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "you're telling me only now?!", variables: [] },
  { text: "Naa kannalani nammakam kaavadam ledhu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "can't believe my eyes!", variables: [] },
  { text: "Ayyababoi! Idi chala risky!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is very risky!", variables: [] },
  { text: "Enti mama! Nuvvu idhi chesav?!", emotion: "surprise", intensity: "high", gender: "male", archetype: "any", context: "bro! you did this?!", variables: [] },
  { text: "Avuno?! Ante nijamgana?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "really?! is it actually true?!", variables: [] },
  { text: "Idi twist ra! Pedda twist!", emotion: "surprise", intensity: "high", gender: "any", archetype: "narrator", context: "this is a twist! big twist!", variables: [] },
  { text: "Chalaa shock ayyindhi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "got a big shock!", variables: [] },
  { text: "Enta! Inthanta?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "how much! this much?!", variables: [] },
  { text: "Plan motham fail ayyindhi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "the whole plan failed!", variables: [] },
  { text: "Evaru chesaru idhi?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "who did this?!", variables: [] },
  { text: "Nak ardam kavatla!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "I don't understand!", variables: [] },
  { text: "Arey! Ye dekh ke mujhko chakkar aa gaya!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "Hyderabadi I got dizzy seeing this!", variables: [] },
  { text: "Nuvvu cheppindhi nijamena?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "is what you said true?!", variables: [] },
  { text: "Adi ippudu jarigindhi?! Elagaa?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "that just happened?! how?!", variables: [] },
  { text: "Amma! Choodu idi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "mom! look at this!", variables: [] },
  { text: "Praanam pothundhi bhayyaa!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "I'm going to die (dramatic)!", variables: [] },
  { text: "Idi jackpot ra! Full jackpot!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is jackpot!", variables: [] },
  { text: "Sapnaa kaadhu kadaa?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "this isn't a dream right?!", variables: [] },
  { text: "Naku theleedhu! Naku emi theleedhu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "I don't know! I know nothing!", variables: [] },
  { text: "Antha maarindi?! Eppudu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything changed?! when?!", variables: [] },
  { text: "Bhale bhale! Idhi kadaa magic!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "great! this is magic!", variables: [] },
  { text: "Enti {name}! Nuvvaa idhi?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what {name}! you did this?!", variables: ["{name}"] },
  { text: "Naaku nammakam kavatledu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "I can't believe it!", variables: [] },
  { text: "Okka nimisham! Idi enti?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "one moment! what is this?!", variables: [] },
  { text: "Secret bayata paddindhi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "the secret is out!", variables: [] },
  { text: "Intha peddadha?! Chaaala peddadhi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "child", context: "this big?! very big!", variables: [] },
  { text: "Ippudu emi cheddaam?!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "what do we do now?!", variables: [] },
  { text: "Nenu kashtapadda kaani... idhi jarigindhi!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "I tried hard but this happened!", variables: [] },
  { text: "Avvala?! Eppudeppudu?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh no?! when when?!", variables: [] },
  { text: "Chetulu kaalputhunnayi ra!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "my hands are shaking!", variables: [] },
  { text: "Idi history ra! History!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "this is history!", variables: [] },
  { text: "Light poyindhi! Andheram!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "power went out! darkness!", variables: [] },
  { text: "Ye {object} idhi enti ra?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "what is this {object}?!", variables: ["{object}"] },
  { text: "Manchi timing ra! Exact ga vacchav!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "good timing! came at the exact moment!", variables: [] },
  { text: "Motham baridhi ayipoyindhi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything went empty!", variables: [] },
  { text: "Impossible ra! Im-pos-si-ble!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "impossible!", variables: [] },
  { text: "Okka second... idi rotta laaga undhi!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "wait, this seems wrong!", variables: [] },
  { text: "Pranam pothundhi shock tho!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "dying from shock!", variables: [] },
  { text: "Manavallu chala fast undaaru!", emotion: "surprise", intensity: "medium", gender: "any", archetype: "any", context: "our people are very fast!", variables: [] },
  { text: "Amma devudaa! Kaapadu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "oh God! save us!", variables: [] },
  { text: "Anni okkasaari jarigipoyayi!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "everything happened at once!", variables: [] },
  { text: "Dabbu! Chala dabbu!", emotion: "surprise", intensity: "high", gender: "any", archetype: "any", context: "money! lots of money!", variables: [] },
  { text: "Enti! Naa phone ekkadhi?!", emotion: "surprise", intensity: "high", gender: "any", archetype: "comic", context: "what! where's my phone?!", variables: [] },

  // ============================================================
  // ANGER (50)
  // ============================================================
  { text: "Chalu chalu! Aapi ra!", emotion: "anger", intensity: "high", gender: "male", archetype: "any", context: "enough! stop it!", variables: [] },
  { text: "Nee valla kaadhu ra!", emotion: "anger", intensity: "high", gender: "male", archetype: "any", context: "it can't happen because of you!", variables: [] },
  { text: "Noru muyyi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "shut your mouth!", variables: [] },
  { text: "Nee saavu nuvvu saavu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "die your own death (mind your business)", variables: [] },
  { text: "Enduku ra naa praanam thisthav!", emotion: "anger", intensity: "high", gender: "male", archetype: "any", context: "why do you take my life!", variables: [] },
  { text: "Naaku kopam vasthundhi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I'm getting angry!", variables: [] },
  { text: "Poo! Naa mundara kanipinchaku!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "go! don't appear before me!", variables: [] },
  { text: "Idi last warning!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "this is the last warning!", variables: [] },
  { text: "Nuvvu edo chesav! Nee valla andharam suffer!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "you did something! we all suffer!", variables: [] },
  { text: "Ilaa ayithey eppudu kuda kaadhu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "if it's like this then never!", variables: [] },
  { text: "Arre! Tujhe toh mein dekh lunga!", emotion: "anger", intensity: "high", gender: "male", archetype: "any", context: "Hyderabadi I'll see to you!", variables: [] },
  { text: "Thappu chesav! Pedda thappu!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "you made a mistake! big mistake!", variables: [] },
  { text: "Naa matalu evadu vinadu?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "nobody listens to me?!", variables: [] },
  { text: "Naaku vishwasam leka poyindhi!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "I've lost trust!", variables: [] },
  { text: "Nuvvu eppudu maaravaa?!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "will you ever change?!", variables: [] },
  { text: "Cheppaanu kadaa! Vinaledu!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "I told you! you didn't listen!", variables: [] },
  { text: "Dabbu ichchi kuda idheena?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "even after paying this is what we get?!", variables: [] },
  { text: "Nuvvu kaadhu ra! Vere evaro!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "not you! someone else!", variables: [] },
  { text: "Neeku sense ledha?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't you have sense?!", variables: [] },
  { text: "Bajaayincha neekku!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I'll thrash you!", variables: [] },
  { text: "Andharini paagal chesthunnaav!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "you're driving everyone crazy!", variables: [] },
  { text: "Naa blood boil avuthundhi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "my blood is boiling!", variables: [] },
  { text: "Idi nee last chance!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "this is your last chance!", variables: [] },
  { text: "Pattinchukora! Padeyyi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't mind it! leave it!", variables: [] },
  { text: "Nee valla naa paristhithi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "because of you my situation!", variables: [] },
  { text: "Dhairiyam undhi neeku?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "do you have the guts?!", variables: [] },
  { text: "Nuv em chesthavo naaku thelsu!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "I know what you're doing!", variables: [] },
  { text: "Nakku chala kopam ga undhi!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "I'm very angry!", variables: [] },
  { text: "Ilaa matladaaku!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "don't talk like that!", variables: [] },
  { text: "Avathala poru!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "get to the other side! go away!", variables: [] },
  { text: "Chal! Naaku nuvvu kadhu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "go! I don't need you!", variables: [] },
  { text: "Malli idhi chesavante...", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "if you do this again...", variables: [] },
  { text: "Nuvvu chala smart anukunthunnav!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "you think you're very smart!", variables: [] },
  { text: "Enough ra! Enough!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "enough!", variables: [] },
  { text: "Evadiki cheppukuntav ra needi?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "who will you complain to?!", variables: [] },
  { text: "Pillalni disturb cheyyaku!", emotion: "anger", intensity: "medium", gender: "any", archetype: "elder", context: "don't disturb the children!", variables: [] },
  { text: "Nenu vadilipettanu ante vadilipettanu!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "when I say I'll leave, I'll leave!", variables: [] },
  { text: "Nuvvu naatho panaga padthunnav!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "you're messing with me!", variables: [] },
  { text: "Intlo cheppanu... antey!", emotion: "anger", intensity: "medium", gender: "any", archetype: "child", context: "I'll tell at home... that's it!", variables: [] },
  { text: "Ippudu cheppu! Em chesav?!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "now tell me! what did you do?!", variables: [] },
  { text: "Nee meedha nammakam poyindhi!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "lost faith in you!", variables: [] },
  { text: "Oorukune! Oorukune!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "keep quiet! keep quiet!", variables: [] },
  { text: "Idi maa area! Ivvala poo!", emotion: "anger", intensity: "high", gender: "any", archetype: "villain", context: "this is our area! leave today!", variables: [] },
  { text: "Thinnga! Thittaali neenu!", emotion: "anger", intensity: "high", gender: "any", archetype: "elder", context: "I should scold you!", variables: [] },
  { text: "Yeh galat hai! Bohot galat!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "Hyderabadi this is wrong!", variables: [] },
  { text: "Control cheskora!", emotion: "anger", intensity: "medium", gender: "any", archetype: "any", context: "control yourself!", variables: [] },
  { text: "Naa patience test cheyyaku!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't test my patience!", variables: [] },
  { text: "Andhariki same problem ichchinaav!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "you gave the same problem to everyone!", variables: [] },
  { text: "Bokka! Peddha bokka chesav!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "hole! you made a big hole (blunder)!", variables: [] },
  { text: "Naa moham chudaku! Poo!", emotion: "anger", intensity: "high", gender: "any", archetype: "any", context: "don't look at my face! go!", variables: [] },

  // ============================================================
  // FEAR (40)
  // ============================================================
  { text: "Amma! Bhayam ga undhi!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "mom! it's scary!", variables: [] },
  { text: "Bhootham! Paaripoo!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "ghost! run!", variables: [] },
  { text: "Devudaa! Kaapadu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "God! save us!", variables: [] },
  { text: "Naaku chala bhayam vesthundhi!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "I'm very scared!", variables: [] },
  { text: "Akkada chudaku! Akkada emi undhi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look there! what's there!", variables: [] },
  { text: "Paripodaam! Jaldi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "let's run! quickly!", variables: [] },
  { text: "Evaru unnaru akkada?!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "who's there?!", variables: [] },
  { text: "Kaalllu vankuthunnayi bhayantho!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "legs trembling with fear!", variables: [] },
  { text: "Ikkadnunchi vellipodaam!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "let's leave from here!", variables: [] },
  { text: "Venakki chuddhu! Paaripoo!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't look back! run!", variables: [] },
  { text: "Arey! Paamuu! Paamuu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "snake! snake!", variables: [] },
  { text: "Intiki vellipodaam! Ippude!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "let's go home! right now!", variables: [] },
  { text: "Adi vasthundhi! Adi vasthundhi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's coming! it's coming!", variables: [] },
  { text: "Daachuko! Twaraga!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "hide! quickly!", variables: [] },
  { text: "Nenu okkadini undaleenu ikkada!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "I can't stay here alone!", variables: [] },
  { text: "Cheyyyi pattukoraa!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "hold my hand!", variables: [] },
  { text: "Antha andhakaram ayyipoyindhi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "everything went dark!", variables: [] },
  { text: "Emi shaddham adi?!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "what sound was that?!", variables: [] },
  { text: "Naa gundhe chala vegam ga kodthundhi!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "my heart is beating very fast!", variables: [] },
  { text: "Help! Evaru ainaa vasthaara?!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "help! is anyone coming?!", variables: [] },
  { text: "Bhayam veyatledu ante... vesthundhi!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "not scared? well... I am!", variables: [] },
  { text: "Aa side ki vellaku! Dangerous!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "don't go that side! dangerous!", variables: [] },
  { text: "Ikkada ekkadainaa daakuko!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "hide somewhere here!", variables: [] },
  { text: "Adi monster ra! Pedha monster!", emotion: "fear", intensity: "high", gender: "any", archetype: "child", context: "it's a monster! big monster!", variables: [] },
  { text: "Thalupu veyyi! Jaldi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "close the door! quickly!", variables: [] },
  { text: "Rathri yeppudu aipothundhi?!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "when will night end?!", variables: [] },
  { text: "Naaku kanapaddindhi! Nijanga!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "I saw something! really!", variables: [] },
  { text: "Sshhh! Shaddham cheyyaku! Vinipisthadhi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "shh! don't make noise! it'll hear!", variables: [] },
  { text: "Idi trap ra! Phasam ayyam!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's a trap! we're caught!", variables: [] },
  { text: "Bayataki daari ledhu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "no way out!", variables: [] },
  { text: "Nuvvu andaru vellipoo! Nenu aaputhaa!", emotion: "fear", intensity: "high", gender: "male", archetype: "hero", context: "you all go! I'll stop it!", variables: [] },
  { text: "Bhayapadaku! Nenu unnanu!", emotion: "fear", intensity: "medium", gender: "any", archetype: "hero", context: "don't be afraid! I'm here!", variables: [] },
  { text: "Ikkada emi theega ledhu!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "something doesn't feel right here!", variables: [] },
  { text: "Naa vaipe chusthundhi! Choodu!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "it's looking at me! look!", variables: [] },
  { text: "Arre! Kuch hila re! Udhar!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "Hyderabadi something moved! there!", variables: [] },
  { text: "Light! Light thecchandi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "light! bring a light!", variables: [] },
  { text: "Ee adavilo puli unnaayi!", emotion: "fear", intensity: "high", gender: "any", archetype: "any", context: "there are tigers in this forest!", variables: [] },
  { text: "Adi kadhalikindhi! Choodu choodu!", emotion: "fear", intensity: "medium", gender: "any", archetype: "any", context: "it moved! look look!", variables: [] },
  { text: "Naaku cheddha kanlu vacchaayi!", emotion: "fear", intensity: "medium", gender: "any", archetype: "child", context: "I had bad dreams!", variables: [] },
  { text: "Pranam pothundhi ra bhayantho!", emotion: "fear", intensity: "high", gender: "any", archetype: "comic", context: "dying from fear!", variables: [] },

  // ============================================================
  // HAPPINESS (50)
  // ============================================================
  { text: "Super ra! Mast undhi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "super! it's great!", variables: [] },
  { text: "Bhale bhale! Chala baagundhi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "great! very good!", variables: [] },
  { text: "Gelichaam! Mana team gelichindhi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "we won! our team won!", variables: [] },
  { text: "Aaha! Idi kadaa nijamaina santhosham!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "this is real happiness!", variables: [] },
  { text: "Party time ra! Celebration!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "party time!", variables: [] },
  { text: "Yeahh! Ayyipoyindhi! Chesaam!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "done! we did it!", variables: [] },
  { text: "Meeru chala baagaa chesaaru!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "you did very well!", variables: [] },
  { text: "Sapnam nijam ayyindhi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "dream came true!", variables: [] },
  { text: "Aha! Idi unbelievable!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "this is unbelievable (happy)!", variables: [] },
  { text: "Laddu panchandi! Santhosham!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "distribute laddus! joy!", variables: [] },
  { text: "Nuvvu genius ra!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're a genius!", variables: [] },
  { text: "Ippudu happy ga undhi naaku!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "I'm happy now!", variables: [] },
  { text: "Best day ever ra!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "best day ever!", variables: [] },
  { text: "Naa kashtam phalinchindhi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "hero", context: "my hard work paid off!", variables: [] },
  { text: "Devudiki thanks!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "thanks to God!", variables: [] },
  { text: "Dance cheddaam ra! Aaj ka din!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "let's dance! today's the day!", variables: [] },
  { text: "Full marks! Full marks vacchaayi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "got full marks!", variables: [] },
  { text: "{name}! Nuvvu chala great ra!", emotion: "happiness", intensity: "high", gender: "any", archetype: "friend", context: "you're very great!", variables: ["{name}"] },
  { text: "Idi winning moment ra!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "this is the winning moment!", variables: [] },
  { text: "Andhariki thanks cheppali!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "must thank everyone!", variables: [] },
  { text: "Chala manchi roju idhi!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "very good day this!", variables: [] },
  { text: "Mana team number one!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "our team is number one!", variables: [] },
  { text: "Santhosham tho kanneeru vasthunnayi!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "tears of joy!", variables: [] },
  { text: "Chudu chudu! Memu chesaam!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "look look! we did it!", variables: [] },
  { text: "Fantastic ra! World class!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "fantastic! world class!", variables: [] },
  { text: "Ice cream thindam! Celebrate cheddaam!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "eat ice cream! celebrate!", variables: [] },
  { text: "Intiki poyi chepputhaa!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "going home to tell everyone!", variables: [] },
  { text: "Amma! Naanu pass ayyanu!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "mom! I passed!", variables: [] },
  { text: "Idi teamwork ra! Pure teamwork!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "mentor", context: "this is teamwork!", variables: [] },
  { text: "Kya baat hai re! Mast kiya!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "Hyderabadi did great!", variables: [] },
  { text: "Records break chesaam ra!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "we broke records!", variables: [] },
  { text: "Idi kuda saadhinchaam!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "we achieved this too!", variables: [] },
  { text: "Baga chesav {name}! Proud of you!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "well done! proud of you!", variables: ["{name}"] },
  { text: "Mana vijayam! Mana garavam!", emotion: "happiness", intensity: "high", gender: "any", archetype: "narrator", context: "our victory! our pride!", variables: [] },
  { text: "Evaranna cheppandi! Santhosham panchukuntaa!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "tell someone! I want to share my joy!", variables: [] },
  { text: "Ee moment ni enjoy cheddaam!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "let's enjoy this moment!", variables: [] },
  { text: "Bravo! Standing ovation!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "bravo!", variables: [] },
  { text: "Meeru andaroo heroes!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "you are all heroes!", variables: [] },
  { text: "Idi special occasion ra!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "this is a special occasion!", variables: [] },
  { text: "Nuvvu nammav kaani... ayyindhi ra!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "you won't believe it... but it happened!", variables: [] },
  { text: "Ammaa naannaa ki chepputhaa!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "I'll tell mom and dad!", variables: [] },
  { text: "Oka cinema laaga undhi life!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "any", context: "life is like a movie!", variables: [] },
  { text: "Mass ra! Peddha mass!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "mass! very mass!", variables: [] },
  { text: "Kashtam tho vacchindhi kaani... worth it ra!", emotion: "happiness", intensity: "medium", gender: "any", archetype: "hero", context: "came with hardship but worth it!", variables: [] },
  { text: "Golden moment!", emotion: "happiness", intensity: "high", gender: "any", archetype: "narrator", context: "golden moment!", variables: [] },
  { text: "Andhariki biryani! Naa treat!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "biryani for everyone! my treat!", variables: [] },
  { text: "Champion! Nuvvu champion!", emotion: "happiness", intensity: "high", gender: "any", archetype: "mentor", context: "you're a champion!", variables: [] },
  { text: "Idi miracle ra! Pure miracle!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "this is a miracle!", variables: [] },
  { text: "Malli malli try cheddaam! Super fun!", emotion: "happiness", intensity: "high", gender: "any", archetype: "child", context: "let's try again! super fun!", variables: [] },
  { text: "Jai Telangana! Jai Andhra!", emotion: "happiness", intensity: "high", gender: "any", archetype: "any", context: "victory chant!", variables: [] },

  // ============================================================
  // THINKING / WISDOM (40)
  // ============================================================
  { text: "Hmm... alochinchali!", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "must think about this", variables: [] },
  { text: "Naaku oka idea vasthundhi!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "I'm getting an idea!", variables: [] },
  { text: "Aagu aagu... naaku ardham avuthundhi!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "wait wait, I'm understanding!", variables: [] },
  { text: "Daani ardham enti ante...", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "what that means is...", variables: [] },
  { text: "Manamu ilaa chesthey?", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "what if we do it like this?", variables: [] },
  { text: "Naaku oka plan undhi!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "hero", context: "I have a plan!", variables: [] },
  { text: "Aalochinchu... {object} lekunte?", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "think... what if this wasn't there?", variables: ["{object}"] },
  { text: "Ardham ayyindha? Nenu cheppindhi?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "did you understand what I said?", variables: [] },
  { text: "Idi chala lota ayna vishayam!", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "this is a very deep matter!", variables: [] },
  { text: "Kashtam lekunte vishayam nerchukomu!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "without difficulty we don't learn!", variables: [] },
  { text: "Anni vaatiki oka reason untadhi!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "everything has a reason!", variables: [] },
  { text: "Aalocinchaku! Cheyyi!", emotion: "thinking", intensity: "high", gender: "any", archetype: "hero", context: "don't think! do it!", variables: [] },
  { text: "Mundhu brain use cheyyi!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "use your brain first!", variables: [] },
  { text: "Aa! Ippudu ardham ayyindhi!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "ah! now I understand!", variables: [] },
  { text: "Vere angle lo cheddaam!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "let's think from another angle!", variables: [] },
  { text: "Thappula nundi nerchukovadam... ade vidya!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "learning from mistakes is the real skill!", variables: [] },
  { text: "Meeku emi anipistundhi?", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "what do you think?", variables: [] },
  { text: "Jagrathaga choodu... ikkada emi undho!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "look carefully, what's here!", variables: [] },
  { text: "Nenu alochisthunna...", emotion: "thinking", intensity: "low", gender: "any", archetype: "any", context: "I'm thinking...", variables: [] },
  { text: "Answer chala simple!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "the answer is very simple!", variables: [] },
  { text: "Problem unte solution kuda untadhi!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "if there's a problem there's a solution!", variables: [] },
  { text: "Wait wait wait! Eureka!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "eureka moment!", variables: [] },
  { text: "Ee connection artham chesuko!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "understand this connection!", variables: [] },
  { text: "Ulta alochinchu! Straightga kaadhu!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "think reverse! not straight!", variables: [] },
  { text: "Practice tho anni saadyam!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "everything possible with practice!", variables: [] },
  { text: "Hmmm... interesting... chala interesting!", emotion: "thinking", intensity: "low", gender: "any", archetype: "villain", context: "villain finding something interesting", variables: [] },
  { text: "Ekkada tappu jarigindhi? Cheddaam!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "where did the mistake happen?", variables: [] },
  { text: "Idi clue! Definitely clue!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "this is a clue!", variables: [] },
  { text: "Ippudu batti velgindhi!", emotion: "thinking", intensity: "high", gender: "any", archetype: "any", context: "now the bulb lit up!", variables: [] },
  { text: "Andhariki cheppandi! Daari dorikindhi!", emotion: "thinking", intensity: "high", gender: "any", archetype: "hero", context: "tell everyone! found the way!", variables: [] },
  { text: "Mundhu question artham chesuko!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "first understand the question!", variables: [] },
  { text: "Ee angle nunchi choodaledu!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "didn't look from this angle!", variables: [] },
  { text: "Idi miss chesaam! Important point!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "any", context: "we missed this! important!", variables: [] },
  { text: "Sabaramu! Sabaram meedha padhalatho!", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "patience! patience bears results!", variables: [] },
  { text: "Jawaab dorikindha neeku?", emotion: "thinking", intensity: "low", gender: "any", archetype: "mentor", context: "did you find the answer?", variables: [] },
  { text: "Konni saarlu oppikovadam lo gelupuntundi!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "sometimes accepting means winning!", variables: [] },
  { text: "Nuvvu neeku kanna ekkuva capable!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "you're more capable than you think!", variables: [] },
  { text: "Idi pattern ra! Chusthunnaavaa?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "this is a pattern! are you seeing?", variables: [] },
  { text: "Brain use cheyyi ra! Brain!", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "use your brain!", variables: [] },
  { text: "Ippudu artham ayyindhi kadaa?", emotion: "thinking", intensity: "medium", gender: "any", archetype: "mentor", context: "now you understand, right?", variables: [] },

  // ============================================================
  // NARRATION (40)
  // ============================================================
  { text: "Tarvatha emi jarigindhi? Vinandi!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "what happened next? listen!", variables: [] },
  { text: "Chala kaalam kritham...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "long long ago...", variables: [] },
  { text: "Ipudu vinandi tarvathi kadhaa!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "now listen to the next story!", variables: [] },
  { text: "Oka ooru lo oka {object} undhi...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "in a village there was a...", variables: ["{object}"] },
  { text: "Kaani kadha ikkada aagadhu!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "but the story doesn't stop here!", variables: [] },
  { text: "Cheddaam enti avuthundho!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "let's see what happens!", variables: [] },
  { text: "Idhi lopala, vere vaaipu...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "meanwhile, on the other side...", variables: [] },
  { text: "Ipudu nijamaiana kadha start!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "now the real story starts!", variables: [] },
  { text: "Konni gantala tarvatha...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "after a few hours...", variables: [] },
  { text: "Idi vini {name}ki chala baadha kaligindhi!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "hearing this, they felt very sad", variables: ["{name}"] },
  { text: "Marnaadu subhodayam...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "next day morning...", variables: [] },
  { text: "Ilaa oka kotha adventure start ayyindhi!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "thus a new adventure started!", variables: [] },
  { text: "Andhariki anipinchindhi ayipoyindhi ani... kaani!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everyone thought it was over... but!", variables: [] },
  { text: "Kaasintha sepu tarvatha...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "after a little while...", variables: [] },
  { text: "Aa roju vacchindhi...", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "that day came...", variables: [] },
  { text: "{name} chesagaladha? Cheddaam!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "can they do it? let's see!", variables: ["{name}"] },
  { text: "Kaalam gaDusthunna kolathee...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "as time kept passing...", variables: [] },
  { text: "Appudu evaru alochinchani vishayam jarigindhi!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "then something unexpected happened!", variables: [] },
  { text: "Gurtundha manaamu emi nerchukunnam? Ippudu upayogam!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "remember what we learned? now useful!", variables: [] },
  { text: "Oka vaaipu... vere vaaipu...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "on one side... on the other...", variables: [] },
  { text: "Appudu... suddenly...", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "then... suddenly...", variables: [] },
  { text: "Antha maaripothundhi!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "everything is about to change!", variables: [] },
  { text: "Mundhu part lo chusaam...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "in the previous part we saw...", variables: [] },
  { text: "Ipudu cheddaam {name} emi chesthaaroo!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "now let's see what they do!", variables: ["{name}"] },
  { text: "Raathri andhakaram aalavarindhi...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "darkness of night spread...", variables: [] },
  { text: "Konni rojulloo...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "in a few days...", variables: [] },
  { text: "Ilaa...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "like this...", variables: [] },
  { text: "Kaani idi kevelam prarambham!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "but this was only the beginning!", variables: [] },
  { text: "Mithrulaaraa! Tarvathi chapter vinandi!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "friends! listen to the next chapter!", variables: [] },
  { text: "Kaani nijamayana sawaalu ippudu start!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "but the real challenge starts now!", variables: [] },
  { text: "Suryodayam tho...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "with sunrise...", variables: [] },
  { text: "Idi anthe kshanam antha maaripoyindhi!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "this was the moment everything changed!", variables: [] },
  { text: "Kadhalo inkoka twist!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "another twist in the story!", variables: [] },
  { text: "Ee kadha hero evaru ante...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "who is the hero of this story...", variables: [] },
  { text: "Kaalam maaripoyindhi... paristhithulu maaripoyaayi...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "times changed... situations changed...", variables: [] },
  { text: "Final round! Aakhri avasaram!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "final round! last chance!", variables: [] },
  { text: "Idi trailer matrame! Cinema inkaa undhi!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "this was just the trailer!", variables: [] },
  { text: "Seedhaga climax ki vellipodaam!", emotion: "narration", intensity: "high", gender: "any", archetype: "narrator", context: "let's go straight to the climax!", variables: [] },
  { text: "Ee kadha gurthu pettukundi!", emotion: "narration", intensity: "medium", gender: "any", archetype: "narrator", context: "remember this story!", variables: [] },
  { text: "Ipudu kadha munduku vellthundhi...", emotion: "narration", intensity: "low", gender: "any", archetype: "narrator", context: "now the story moves forward...", variables: [] },

  // ============================================================
  // MORAL DELIVERY (40)
  // ============================================================
  { text: "Anduvalla antaaru... kashtam chesthey phalitham vasthadhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "hard work brings results!", variables: [] },
  { text: "Paatham emitante... abaddham cheppakudadhu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "lesson: don't lie!", variables: [] },
  { text: "Pillalapaa! Ivvala emi nerchukunnam?", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "kids! what did we learn today?", variables: [] },
  { text: "Nijam yeppudu gelusthadhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "truth always wins!", variables: [] },
  { text: "Sneham ante pedda balam!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "friendship is great strength!", variables: [] },
  { text: "Dhairyam vadhalaku eppudu!", emotion: "moral", intensity: "high", gender: "any", archetype: "mentor", context: "never let go of courage!", variables: [] },
  { text: "Peddhavallu cheppindhi vinali!", emotion: "moral", intensity: "low", gender: "any", archetype: "elder", context: "listen to what elders say!", variables: [] },
  { text: "Thwaraga chesthe thappu avuthundhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "doing things in haste leads to mistakes!", variables: [] },
  { text: "Okkatai unte... balam ekkuva!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "unity means more strength!", variables: [] },
  { text: "Aashapaddadam cheddhu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "greed is bad!", variables: [] },
  { text: "Kasthakaalam lo nijamaiana snehithulu kanipisthaaru!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "true friends show in hard times!", variables: [] },
  { text: "Itharulaku sahayam chesthe... manaku kuda vasthadhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "help others and help comes to you!", variables: [] },
  { text: "Bhayam tarvatha gelupuntadhi!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "victory lies beyond fear!", variables: [] },
  { text: "Chinna chinna vishayaalu pedda maarupuni thesthaayi!", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "small things bring big changes!", variables: [] },
  { text: "Thappuni oppukovadam lo dhairyam untadhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "admitting mistakes takes courage!", variables: [] },
  { text: "Vidyaku vayassu undadhu!", emotion: "moral", intensity: "low", gender: "any", archetype: "mentor", context: "there's no age for learning!", variables: [] },
  { text: "Kalisi chesthe... anni saadyam!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "together everything is possible!", variables: [] },
  { text: "Ee paatham gurthu pettukundi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "remember this lesson!", variables: [] },
  { text: "Ee kadha manaku chepthundhi...", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "this story tells us...", variables: [] },
  { text: "Paryavarananni kaapaadam mana baadyatha!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "protecting environment is our duty!", variables: [] },
  { text: "Dabbu vasthadhi pothundhi... gauravam undali!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "money comes and goes, maintain respect!", variables: [] },
  { text: "Nijamaina hridayam tho adighithey... thappakundaa vasthadhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "ask with true heart and you'll receive!", variables: [] },
  { text: "Prati samasyaku parishkaaram untadhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "every problem has a solution!", variables: [] },
  { text: "Nerchukovadam aapaku eppudu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "never stop learning!", variables: [] },
  { text: "Emi jarigina... nijam cheppu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "no matter what, speak truth!", variables: [] },
  { text: "Nee pani meeda dhyaanam pettu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "focus on your work!", variables: [] },
  { text: "Life lo shortcuts pani cheyyavvu!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "shortcuts don't work in life!", variables: [] },
  { text: "Evvarni chinnaga choodaku!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "don't underestimate anyone!", variables: [] },
  { text: "Oppukunevaallu eppudu gelavvu!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "those who give up never win!", variables: [] },
  { text: "Samayam vidhi ga vaaduko!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "use time wisely!", variables: [] },
  { text: "Amma naannala seva pedda dharmam!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "serving parents is the greatest duty!", variables: [] },
  { text: "Vijayaniki daaari kashtam guDa!", emotion: "moral", intensity: "medium", gender: "any", archetype: "mentor", context: "path to success goes through difficulty!", variables: [] },
  { text: "Nijaayanithii manchi neeti!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "honesty is the best policy!", variables: [] },
  { text: "Sapnaalu veduku! Nerchukundhaam!", emotion: "moral", intensity: "high", gender: "any", archetype: "mentor", context: "chase dreams! keep learning!", variables: [] },
  { text: "Sabaram kotha palitham thesthundhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "patience brings new results!", variables: [] },
  { text: "Mithrulaaraa! Emi nerchukunnaaru?", emotion: "moral", intensity: "low", gender: "any", archetype: "narrator", context: "friends! what did you learn?", variables: [] },
  { text: "Manchi chesthe... manchi vasthadhi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "elder", context: "do good, get good!", variables: [] },
  { text: "Nijaayanithii vaipe nilabadandi!", emotion: "moral", intensity: "high", gender: "any", archetype: "narrator", context: "stand on the side of truth!", variables: [] },
  { text: "Tarvatha episode lo inkaa nerchukundaam! Bye!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "we'll learn more in the next episode!", variables: [] },
  { text: "Ee kadha nachithey... share cheyandi!", emotion: "moral", intensity: "medium", gender: "any", archetype: "narrator", context: "if you liked this story, share!", variables: [] },

  // ============================================================
  // CATCHPHRASE + FILLER + OTHER (remaining ~70 lines)
  // ============================================================
  { text: "Naa peru {name}! Nenu yeppudu ready!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "hero intro", variables: ["{name}"] },
  { text: "Idi naa specialty!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "this is my specialty", variables: [] },
  { text: "Hm hm hm... plan work avuthundhi!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "villain", context: "villain scheming", variables: [] },
  { text: "Meerantha naanu aapaleeru!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "none of you can stop me!", variables: [] },
  { text: "Nenu cheppanu kadaa! Nenu yeppudu correct!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "mentor", context: "I told you! I'm always right!", variables: [] },
  { text: "Oho! Malli ichikkulu!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "oh! trouble again!", variables: [] },
  { text: "Naaku aakali vesindhi!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "I'm hungry!", variables: [] },
  { text: "Worry avvaku! {name} unnadu kadaa!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "don't worry! I'm here!", variables: ["{name}"] },
  { text: "Parvaledhu! Malli try cheddaam!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "no problem! let's try again!", variables: [] },
  { text: "Mundhu bhojanam! Migatha anni tarvatha!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "food first! everything else later!", variables: [] },
  { text: "Mission start!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "mission start!", variables: [] },
  { text: "Idi pillala aata ra!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "this is child's play!", variables: [] },
  { text: "Nenu {name}! Idi naa team!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "I'm {name}! this is my team!", variables: ["{name}"] },
  { text: "Hoshiyaar! {name} vachesadu!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "beware! {name} has come!", variables: ["{name}"] },
  { text: "Lagta hai nene cheyyaali!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "hero", context: "seems like I have to do it!", variables: [] },
  { text: "Power up!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "power up!", variables: [] },
  { text: "Game over, villains!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "game over villains!", variables: [] },
  { text: "Hehehehe! Naa balam lo phasaaru!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "caught in my trap!", variables: [] },
  { text: "Nenu thirigivasthaa!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "villain", context: "I will return!", variables: [] },
  { text: "Full power tho! Let's go!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "with full power!", variables: [] },
  { text: "Manamu okkate! Manamu okkate!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "we are one!", variables: [] },
  { text: "Nenu haar accept cheyyanu!", emotion: "catchphrase", intensity: "high", gender: "any", archetype: "hero", context: "I won't accept defeat!", variables: [] },
  { text: "Bhojanam ekkada?!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "where's the food?!", variables: [] },
  { text: "Tension teesko maku!", emotion: "catchphrase", intensity: "medium", gender: "any", archetype: "comic", context: "don't take tension!", variables: [] },
  // FILLERS
  { text: "Sare sare!", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "okay okay", variables: [] },
  { text: "Cheppura!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "tell me!", variables: [] },
  { text: "Aagu aagu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "wait wait!", variables: [] },
  { text: "Adhi kadhu...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "that's not it...", variables: [] },
  { text: "Hmm... correct!", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "hmm correct!", variables: [] },
  { text: "Choodu choodu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "look look!", variables: [] },
  { text: "Vinu vinu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "listen listen!", variables: [] },
  { text: "Ante...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "I mean...", variables: [] },
  { text: "Avunu avunu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "yes yes!", variables: [] },
  { text: "Kadhu kadhu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "no no!", variables: [] },
  { text: "Raara!", emotion: "filler", intensity: "medium", gender: "male", archetype: "any", context: "come!", variables: [] },
  { text: "Poo!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "go!", variables: [] },
  { text: "Okka nimisham!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "one moment!", variables: [] },
  { text: "Telusu telusu!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "I know I know!", variables: [] },
  { text: "Next!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "next!", variables: [] },
  { text: "Simple!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "simple!", variables: [] },
  { text: "Done ra!", emotion: "filler", intensity: "medium", gender: "any", archetype: "any", context: "done!", variables: [] },
  { text: "Ready aa?", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "ready?", variables: [] },
  { text: "Basically...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "basically", variables: [] },
  { text: "Actually...", emotion: "filler", intensity: "low", gender: "any", archetype: "any", context: "actually", variables: [] },
  // ENCOURAGEMENT
  { text: "Nuvvu cheyagalav!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "you can do it!", variables: [] },
  { text: "Dhairyam vaddalaku!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "don't lose courage!", variables: [] },
  { text: "Malli try cheyyi!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "try again!", variables: [] },
  { text: "Nenu nee vaipe unnanu!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "friend", context: "I'm on your side!", variables: [] },
  { text: "Baga chesav! Inkaa baaga cheyyi!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "did well! do even better!", variables: [] },
  { text: "Gelupuntadhi dhaggarlo undhi!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "victory is very near!", variables: [] },
  { text: "Bhale babu! Baaga chesav!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "elder", context: "well done child!", variables: [] },
  { text: "Nuvvu chala brave!", emotion: "encouragement", intensity: "medium", gender: "any", archetype: "mentor", context: "you're very brave!", variables: [] },
  { text: "Manamu andharam nee vaipe!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "friend", context: "we're all on your side!", variables: [] },
  { text: "Inkonchem! Bas inkonchem!", emotion: "encouragement", intensity: "high", gender: "any", archetype: "mentor", context: "a little more! just a little more!", variables: [] },
  // DETERMINATION
  { text: "Ippudu aaganu!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "won't stop now!", variables: [] },
  { text: "Nenu chesi chupistaa!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "I will prove it!", variables: [] },
  { text: "Emi jarigina sarey!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "no matter what!", variables: [] },
  { text: "Idi naa promise!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "this is my promise!", variables: [] },
  { text: "Full power lagaandi!", emotion: "determination", intensity: "high", gender: "any", archetype: "hero", context: "apply full power!", variables: [] },
  // WARNING
  { text: "Jagratha! Pramaadam!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "careful! danger!", variables: [] },
  { text: "Akkadiki vellaku! Apaayu!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "don't go there! dangerous!", variables: [] },
  { text: "Sambhalko! Kindha choodu!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "careful! look down!", variables: [] },
  { text: "Thakku! Thakku! Venapaku!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "back! back! get back!", variables: [] },
  { text: "Idi last warning!", emotion: "warning", intensity: "high", gender: "any", archetype: "any", context: "this is the last warning!", variables: [] },
  // GRATITUDE
  { text: "Thanks ra! Chala help ayyindhi!", emotion: "gratitude", intensity: "medium", gender: "any", archetype: "any", context: "thanks! it helped a lot!", variables: [] },
  { text: "Dhanyavadaalu! Hridayapoorvakamga!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "heartfelt thanks!", variables: [] },
  { text: "Nuvvu lekunte nenu undanu!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "any", context: "without you I wouldn't exist!", variables: [] },
  { text: "Devudu neeku manchi cheyugaaka!", emotion: "gratitude", intensity: "medium", gender: "any", archetype: "elder", context: "may God bless you!", variables: [] },
  { text: "{name}! Nuvvu best friend ra!", emotion: "gratitude", intensity: "high", gender: "any", archetype: "friend", context: "you're the best friend!", variables: ["{name}"] },
  // CELEBRATION
  { text: "Party time ra! Celebration!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "party time!", variables: [] },
  { text: "Gelichaam! Gelichaam! Champions!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "we won! champions!", variables: [] },
  { text: "Laddu panchandi! Santhosham!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "distribute laddus!", variables: [] },
  { text: "Hip hip hurray!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "hip hip hooray!", variables: [] },
  { text: "Badhaai ho! Badhaai ho!", emotion: "celebration", intensity: "high", gender: "any", archetype: "any", context: "congratulations!", variables: [] },
];

export const teluguBank: DialogueBank = {
  language: 'telugu',
  isoCode: 'te-IN',
  displayName: 'Telugu',
  lines,
};
