#!/usr/bin/env tsx
/**
 * quality-gate-report.ts — Pretty markdown report from quality gate JSON artifact.
 *
 * Usage:
 *   npx tsx scripts/quality-gate-report.ts quality-gate-report.json [--output=report.md]
 *
 * Used in GitHub Actions to post the report as a PR comment.
 */

import * as fs from 'fs';
import type { QualityReport, CheckResult, Severity } from './quality-gate';

const SEVERITY_EMOJI: Record<Severity, string> = {
  PASS:  '✅',
  WARN:  '⚠️',
  ERROR: '❌',
  FATAL: '🛑',
};

const CATEGORY_LABELS: Record<CheckResult['category'], string> = {
  format:      '📐 Format',
  visual:      '👁️ Visual',
  retention:   '📈 Retention',
  metadata:    '🏷️ Metadata',
  determinism: '🔒 Determinism',
};

function buildReport(report: QualityReport): string {
  const statusBanner = report.overallPassed
    ? '## ✅ Quality Gate PASSED — Video approved for upload'
    : '## 🛑 Quality Gate FAILED — Upload BLOCKED';

  const modeNote = report.enforceMode === 'warn'
    ? '\n> ⚠️ **Warn mode active** (`QUALITY_GATE_ENFORCE=warn`): only FATAL issues block upload. Switch to `enforce` before going live.\n'
    : '';

  const summaryTable = [
    '| Metric | Value |',
    '|---|---|',
    `| Video | \`${report.videoPath}\` |`,
    `| Format | ${report.format === 'long' ? 'Long-form (16:9)' : 'Short (9:16)'} |`,
    `| SHA256 | \`${report.videoSha256.slice(0, 16)}...\` |`,
    `| Timestamp | ${report.timestamp} |`,
    `| Gate duration | ${(report.durationMs / 1000).toFixed(1)}s |`,
    `| Checks total | ${report.summary.total} |`,
    `| ✅ Passed | ${report.summary.passed} |`,
    `| 🛑 Fatal | ${report.summary.fatal} |`,
    `| ❌ Errors | ${report.summary.errors} |`,
    `| ⚠️ Warnings | ${report.summary.warnings} |`,
  ].join('\n');

  // Group by category
  const byCategory = new Map<CheckResult['category'], CheckResult[]>();
  for (const check of report.checks) {
    const list = byCategory.get(check.category) ?? [];
    list.push(check);
    byCategory.set(check.category, list);
  }

  const categoryOrder: CheckResult['category'][] = ['format', 'visual', 'retention', 'metadata', 'determinism'];

  const checkSections = categoryOrder
    .filter(cat => byCategory.has(cat))
    .map(cat => {
      const checks = byCategory.get(cat)!;
      const allPass = checks.every(c => c.passed);
      const catStatus = allPass ? '✅' : checks.some(c => c.severity === 'FATAL') ? '🛑' : '❌';

      const rows = checks.map(c => {
        const emoji = SEVERITY_EMOJI[c.passed ? 'PASS' : c.severity];
        const details = c.measured
          ? `<br><sub>Measured: \`${JSON.stringify(c.measured).slice(0, 80)}\`</sub>`
          : '';
        return `| ${emoji} | \`${c.checkId}\` | ${c.name} | ${c.message}${details} |`;
      }).join('\n');

      return [
        `<details${allPass ? '' : ' open'}>`,
        `<summary>${catStatus} ${CATEGORY_LABELS[cat]} (${checks.filter(c => c.passed).length}/${checks.length} passed)</summary>`,
        '',
        '| Status | ID | Check | Result |',
        '|---|---|---|---|',
        rows,
        '',
        '</details>',
      ].join('\n');
    }).join('\n\n');

  // Failed checks callout
  const failedChecks = report.checks.filter(c => !c.passed);
  const failedCallout = failedChecks.length === 0 ? '' : [
    '',
    '---',
    '',
    '## 🚨 Failed Checks — Action Required',
    '',
    failedChecks.map(c => {
      const threshStr = c.threshold
        ? `\n  - **Threshold:** \`${JSON.stringify(c.threshold)}\``
        : '';
      const measuredStr = c.measured
        ? `\n  - **Measured:** \`${JSON.stringify(c.measured)}\``
        : '';
      return [
        `### ${SEVERITY_EMOJI[c.severity]} \`${c.checkId}\` — ${c.name}`,
        `- **Severity:** ${c.severity}`,
        `- **Category:** ${CATEGORY_LABELS[c.category]}`,
        `- **Message:** ${c.message}`,
        measuredStr,
        threshStr,
      ].filter(Boolean).join('\n');
    }).join('\n\n'),
  ].join('\n');

  const footer = [
    '',
    '---',
    '',
    '<sub>Generated by quality-gate.ts — Every threshold is cited in CHECKLIST.md.</sub>',
    `<sub>Artifact: \`quality-gate-report.json\` | Mode: \`${report.enforceMode}\`</sub>`,
  ].join('\n');

  return [
    statusBanner,
    modeNote,
    '',
    '### Summary',
    '',
    summaryTable,
    '',
    '---',
    '',
    '### Check Results by Category',
    '',
    checkSections,
    failedCallout,
    footer,
  ].join('\n');
}

if (require.main === module) {
  const args = process.argv.slice(2);
  const reportPath = args[0];
  const outputArg = args.find(a => a.startsWith('--output='))?.split('=')[1];

  if (!reportPath) {
    console.error('Usage: npx tsx scripts/quality-gate-report.ts <report.json> [--output=report.md]');
    process.exit(1);
  }

  if (!fs.existsSync(reportPath)) {
    console.error(`Report not found: ${reportPath}`);
    process.exit(1);
  }

  const report: QualityReport = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));
  const markdown = buildReport(report);

  if (outputArg) {
    fs.writeFileSync(outputArg, markdown);
    console.log(`Report written to: ${outputArg}`);
  } else {
    console.log(markdown);
  }
}

export { buildReport };
